


//
// NOTE This file is autogenerated! Do not manually edit this!      
//

package org.fusesource.ide.generator

/*
object Dimensions {

  val dimensions = Map(
    "node.bean.svg" -> Dimension("node.bean.svg", 103.748, 51.339)
,    "node.choice.svg" -> Dimension("node.choice.svg", 58.5, 36)
,    "node.diagram.svg" -> Dimension("node.diagram.svg", 80, 80)
,    "node.endpoint.svg" -> Dimension("node.endpoint.svg", 103.748, 51.339)
,    "node.filter.svg" -> Dimension("node.filter.svg", 58.5, 36)
,    "node.generic.svg" -> Dimension("node.generic.svg", 58.5, 36)
,    "node.log.svg" -> Dimension("node.log.svg", 103.748, 51.339)
,    "node.process.svg" -> Dimension("node.process.svg", 103.748, 51.339)
,    "node.transform.svg" -> Dimension("node.transform.svg", 58.5, 36)
,    "node.when.svg" -> Dimension("node.when.svg", 58.5, 36)
  )
}*/
