/*******************************************************************************
 * Copyright (c) 2017 Red Hat, Inc. 
 * Distributed under license by Red Hat, Inc. All rights reserved. 
 * This program is made available under the terms of the 
 * Eclipse Public License v1.0 which accompanies this distribution, 
 * and is available at http://www.eclipse.org/legal/epl-v10.html 
 * 
 * Contributors: 
 * Red Hat, Inc. - initial API and implementation 
 ******************************************************************************/ 
package org.fusesource.ide.wsdl2rest.ui.wizard;

import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeSupport;

/**
 * Collects the various data points needed for the wsdl2rest utility.
 * @author brianf
 *
 */
public class Wsdl2RestOptions {

	private String wsdlURL;
	private String projectName;
	private String destinationJava;
	private String destinationCamel;
	private String targetServiceAddress;
	private String targetRestServiceAddress;

	private final PropertyChangeSupport changeSupport = new PropertyChangeSupport(this);

	/**
	 * URL to the WSDL to be processed by the wsdl2rest utility.
	 * @return String
	 */
	public String getWsdlURL() {
		return wsdlURL;
	}

	/**
	 * Set URL to the WSDL to be processed by the wsdl2rest utility.
	 * @param wsdlURL
	 */
	public void setWsdlURL(String wsdlURL) {
		firePropertyChange("wsdlURL", this.wsdlURL, this.wsdlURL = wsdlURL); //$NON-NLS-1$
	}

	/**
	 * Project used for the destination of the files generated by the wsdl2rest utility.
	 * @return String
	 */
	public String getProjectName() {
		return projectName;
	}

	/**
	 * Set Project used for the destination of the files generated by the wsdl2rest utility.
	 * @param projectName
	 */
	public void setProjectName(String projectName) {
		firePropertyChange("projectName", this.projectName, this.projectName = projectName); //$NON-NLS-1$
	}

	/**
	 * Destination of the Java files generated by the wsdl2rest utility.
	 * @return String
	 */
	public String getDestinationJava() {
		return destinationJava;
	}

	/**
	 * Set Destination of the Java files generated by the wsdl2rest utility.
	 * @param destinationJava
	 */
	public void setDestinationJava(String destinationJava) {
		firePropertyChange("destinationJava", this.destinationJava, this.destinationJava = destinationJava); //$NON-NLS-1$
	}

	/**
	 * Destination of the Camel files generated by the wsdl2rest utility.
	 * @return String
	 */
	public String getDestinationCamel() {
		return destinationCamel;
	}

	/**
	 * Set Destination of the Camel configuration generated by the wsdl2rest utility.
	 * @param destinationCamel
	 */
	public void setDestinationCamel(String destinationCamel) {
		firePropertyChange("destinationCamel", this.destinationCamel, this.destinationCamel = destinationCamel); //$NON-NLS-1$
	}

	/**
	 * Target Service Address used by the wsdl2rest utility.
	 * @return String
	 */
	public String getTargetServiceAddress() {
		return targetServiceAddress;
	}

	/**
	 * Set Target Service Address used by the wsdl2rest utility.
	 * @param targetServiceAddress
	 */
	public void setTargetServiceAddress(String targetServiceAddress) {
		firePropertyChange("targetServiceAddress", this.targetServiceAddress, this.targetServiceAddress = targetServiceAddress); //$NON-NLS-1$
	}

	/**
	 * Target Rest Service Address used by the wsdl2rest utility.
	 * @return String
	 */
	public String getTargetRestServiceAddress() {
		return targetRestServiceAddress;
	}

	/**
	 * Set Target Rest Service Address used by the wsdl2rest utility.
	 * @param targetServiceAddress
	 */
	public void setTargetRestServiceAddress(String targetRestServiceAddress) {
		firePropertyChange("targetRestServiceAddress", this.targetRestServiceAddress, this.targetRestServiceAddress = targetRestServiceAddress); //$NON-NLS-1$
	}

	/**
	 * @param listener
	 */
	public void addPropertyChangeListener(PropertyChangeListener listener) {
		changeSupport.addPropertyChangeListener(listener);
	}

	/**
	 * @param listener
	 */
	public void removePropertyChangeListener(PropertyChangeListener listener) {
		changeSupport.removePropertyChangeListener(listener);
	}

	/**
	 * @param propertyName
	 * @param oldValue
	 * @param newValue
	 */
	protected void firePropertyChange(String propertyName, Object oldValue, Object newValue) {
		changeSupport.firePropertyChange(propertyName, oldValue, newValue);
	}
}
