//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.13 at 12:09:41 PM EST 
//


package org.jboss.mapper.camel.blueprint;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for base64DataFormat complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="base64DataFormat">
 *   &lt;complexContent>
 *     &lt;extension base="{http://camel.apache.org/schema/blueprint}dataFormat">
 *       &lt;sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="lineLength" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="lineSeparator" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="urlSafe" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "base64DataFormat")
public class Base64DataFormat
    extends DataFormat
{

    @XmlAttribute(name = "lineLength")
    protected Integer lineLength;
    @XmlAttribute(name = "lineSeparator")
    protected String lineSeparator;
    @XmlAttribute(name = "urlSafe")
    protected Boolean urlSafe;

    /**
     * Gets the value of the lineLength property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getLineLength() {
        return lineLength;
    }

    /**
     * Sets the value of the lineLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLineLength(Integer value) {
        this.lineLength = value;
    }

    /**
     * Gets the value of the lineSeparator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLineSeparator() {
        return lineSeparator;
    }

    /**
     * Sets the value of the lineSeparator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLineSeparator(String value) {
        this.lineSeparator = value;
    }

    /**
     * Gets the value of the urlSafe property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUrlSafe() {
        return urlSafe;
    }

    /**
     * Sets the value of the urlSafe property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUrlSafe(Boolean value) {
        this.urlSafe = value;
    }

}
