//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.13 at 12:09:41 PM EST 
//


package org.jboss.mapper.camel.blueprint;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for camelContextFactoryBean complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="camelContextFactoryBean">
 *   &lt;complexContent>
 *     &lt;extension base="{http://camel.apache.org/schema/blueprint}abstractCamelContextFactoryBean">
 *       &lt;sequence>
 *         &lt;element ref="{http://camel.apache.org/schema/blueprint}properties" minOccurs="0"/>
 *         &lt;element ref="{http://camel.apache.org/schema/blueprint}propertyPlaceholder" minOccurs="0"/>
 *         &lt;element name="package" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://camel.apache.org/schema/blueprint}packageScan" minOccurs="0"/>
 *         &lt;element ref="{http://camel.apache.org/schema/blueprint}contextScan" minOccurs="0"/>
 *         &lt;element ref="{http://camel.apache.org/schema/blueprint}jmxAgent" minOccurs="0"/>
 *         &lt;element ref="{http://camel.apache.org/schema/blueprint}streamCaching" minOccurs="0"/>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}template"/>
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}consumerTemplate"/>
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}proxy"/>
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}export"/>
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}errorHandler"/>
 *         &lt;/choice>
 *         &lt;element ref="{http://camel.apache.org/schema/blueprint}routeBuilder" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://camel.apache.org/schema/blueprint}routeContextRef" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://camel.apache.org/schema/blueprint}restContextRef" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://camel.apache.org/schema/blueprint}threadPoolProfile" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://camel.apache.org/schema/blueprint}threadPool" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://camel.apache.org/schema/blueprint}endpoint" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://camel.apache.org/schema/blueprint}dataFormats" minOccurs="0"/>
 *         &lt;element ref="{http://camel.apache.org/schema/blueprint}redeliveryPolicyProfile" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://camel.apache.org/schema/blueprint}onException" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://camel.apache.org/schema/blueprint}onCompletion" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://camel.apache.org/schema/blueprint}intercept" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://camel.apache.org/schema/blueprint}interceptFrom" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="interceptSendToEndpoint" type="{http://camel.apache.org/schema/blueprint}interceptSendToEndpointDefinition" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://camel.apache.org/schema/blueprint}restConfiguration" minOccurs="0"/>
 *         &lt;element ref="{http://camel.apache.org/schema/blueprint}rest" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://camel.apache.org/schema/blueprint}route" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="depends-on" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="trace" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="messageHistory" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="streamCache" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="delayer" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="handleFault" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="errorHandlerRef" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="autoStartup" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="useMDCLogging" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="useBreadcrumb" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="allowUseOriginalMessage" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="runtimeEndpointRegistryEnabled" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="managementNamePattern" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="threadNamePattern" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="useBlueprintPropertyResolver" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="shutdownRoute" type="{http://camel.apache.org/schema/blueprint}shutdownRoute" />
 *       &lt;attribute name="shutdownRunningTask" type="{http://camel.apache.org/schema/blueprint}shutdownRunningTask" />
 *       &lt;attribute name="lazyLoadTypeConverters" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="typeConverterStatisticsEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "camelContextFactoryBean", propOrder = {
    "properties",
    "propertyPlaceholder",
    "_package",
    "packageScan",
    "contextScan",
    "jmxAgent",
    "streamCaching",
    "templateOrConsumerTemplateOrProxy",
    "routeBuilder",
    "routeContextRef",
    "restContextRef",
    "threadPoolProfile",
    "threadPool",
    "endpoint",
    "dataFormats",
    "redeliveryPolicyProfile",
    "onException",
    "onCompletion",
    "intercept",
    "interceptFrom",
    "interceptSendToEndpoint",
    "restConfiguration",
    "rest",
    "route"
})
public class CamelContextFactoryBean
    extends AbstractCamelContextFactoryBean
{

    protected PropertiesDefinition properties;
    protected CamelPropertyPlaceholderDefinition propertyPlaceholder;
    @XmlElement(name = "package")
    protected List<String> _package;
    protected PackageScanDefinition packageScan;
    protected ContextScanDefinition contextScan;
    protected CamelJMXAgentDefinition jmxAgent;
    protected CamelStreamCachingStrategyDefinition streamCaching;
    @XmlElements({
        @XmlElement(name = "template", type = CamelProducerTemplateFactoryBean.class),
        @XmlElement(name = "consumerTemplate", type = CamelConsumerTemplateFactoryBean.class),
        @XmlElement(name = "proxy", nillable = true),
        @XmlElement(name = "export", type = CamelServiceExporterDefinition.class),
        @XmlElement(name = "errorHandler", type = CamelErrorHandlerFactoryBean.class)
    })
    protected List<Object> templateOrConsumerTemplateOrProxy;
    protected List<RouteBuilderDefinition> routeBuilder;
    protected List<RouteContextRefDefinition> routeContextRef;
    protected List<RestContextRefDefinition> restContextRef;
    protected List<ThreadPoolProfileDefinition> threadPoolProfile;
    protected List<CamelThreadPoolFactoryBean> threadPool;
    protected List<CamelEndpointFactoryBean> endpoint;
    protected DataFormatsDefinition dataFormats;
    protected List<CamelRedeliveryPolicyFactoryBean> redeliveryPolicyProfile;
    protected List<OnExceptionDefinition> onException;
    protected List<OnCompletionDefinition> onCompletion;
    protected List<InterceptDefinition> intercept;
    protected List<InterceptFromDefinition> interceptFrom;
    protected List<InterceptSendToEndpointDefinition> interceptSendToEndpoint;
    protected RestConfigurationDefinition restConfiguration;
    protected List<RestDefinition> rest;
    protected List<RouteDefinition> route;
    @XmlAttribute(name = "depends-on")
    protected String dependsOn;
    @XmlAttribute(name = "trace")
    protected String trace;
    @XmlAttribute(name = "messageHistory")
    protected String messageHistory;
    @XmlAttribute(name = "streamCache")
    protected String streamCache;
    @XmlAttribute(name = "delayer")
    protected String delayer;
    @XmlAttribute(name = "handleFault")
    protected String handleFault;
    @XmlAttribute(name = "errorHandlerRef")
    protected String errorHandlerRef;
    @XmlAttribute(name = "autoStartup")
    protected String autoStartup;
    @XmlAttribute(name = "useMDCLogging")
    protected String useMDCLogging;
    @XmlAttribute(name = "useBreadcrumb")
    protected String useBreadcrumb;
    @XmlAttribute(name = "allowUseOriginalMessage")
    protected String allowUseOriginalMessage;
    @XmlAttribute(name = "runtimeEndpointRegistryEnabled")
    protected String runtimeEndpointRegistryEnabled;
    @XmlAttribute(name = "managementNamePattern")
    protected String managementNamePattern;
    @XmlAttribute(name = "threadNamePattern")
    protected String threadNamePattern;
    @XmlAttribute(name = "useBlueprintPropertyResolver")
    protected Boolean useBlueprintPropertyResolver;
    @XmlAttribute(name = "shutdownRoute")
    protected ShutdownRoute shutdownRoute;
    @XmlAttribute(name = "shutdownRunningTask")
    protected ShutdownRunningTask shutdownRunningTask;
    @XmlAttribute(name = "lazyLoadTypeConverters")
    protected Boolean lazyLoadTypeConverters;
    @XmlAttribute(name = "typeConverterStatisticsEnabled")
    protected Boolean typeConverterStatisticsEnabled;

    /**
     * Gets the value of the properties property.
     * 
     * @return
     *     possible object is
     *     {@link PropertiesDefinition }
     *     
     */
    public PropertiesDefinition getProperties() {
        return properties;
    }

    /**
     * Sets the value of the properties property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertiesDefinition }
     *     
     */
    public void setProperties(PropertiesDefinition value) {
        this.properties = value;
    }

    /**
     * Gets the value of the propertyPlaceholder property.
     * 
     * @return
     *     possible object is
     *     {@link CamelPropertyPlaceholderDefinition }
     *     
     */
    public CamelPropertyPlaceholderDefinition getPropertyPlaceholder() {
        return propertyPlaceholder;
    }

    /**
     * Sets the value of the propertyPlaceholder property.
     * 
     * @param value
     *     allowed object is
     *     {@link CamelPropertyPlaceholderDefinition }
     *     
     */
    public void setPropertyPlaceholder(CamelPropertyPlaceholderDefinition value) {
        this.propertyPlaceholder = value;
    }

    /**
     * Gets the value of the package property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the package property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPackage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getPackage() {
        if (_package == null) {
            _package = new ArrayList<String>();
        }
        return this._package;
    }

    /**
     * Gets the value of the packageScan property.
     * 
     * @return
     *     possible object is
     *     {@link PackageScanDefinition }
     *     
     */
    public PackageScanDefinition getPackageScan() {
        return packageScan;
    }

    /**
     * Sets the value of the packageScan property.
     * 
     * @param value
     *     allowed object is
     *     {@link PackageScanDefinition }
     *     
     */
    public void setPackageScan(PackageScanDefinition value) {
        this.packageScan = value;
    }

    /**
     * Gets the value of the contextScan property.
     * 
     * @return
     *     possible object is
     *     {@link ContextScanDefinition }
     *     
     */
    public ContextScanDefinition getContextScan() {
        return contextScan;
    }

    /**
     * Sets the value of the contextScan property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContextScanDefinition }
     *     
     */
    public void setContextScan(ContextScanDefinition value) {
        this.contextScan = value;
    }

    /**
     * Gets the value of the jmxAgent property.
     * 
     * @return
     *     possible object is
     *     {@link CamelJMXAgentDefinition }
     *     
     */
    public CamelJMXAgentDefinition getJmxAgent() {
        return jmxAgent;
    }

    /**
     * Sets the value of the jmxAgent property.
     * 
     * @param value
     *     allowed object is
     *     {@link CamelJMXAgentDefinition }
     *     
     */
    public void setJmxAgent(CamelJMXAgentDefinition value) {
        this.jmxAgent = value;
    }

    /**
     * Gets the value of the streamCaching property.
     * 
     * @return
     *     possible object is
     *     {@link CamelStreamCachingStrategyDefinition }
     *     
     */
    public CamelStreamCachingStrategyDefinition getStreamCaching() {
        return streamCaching;
    }

    /**
     * Sets the value of the streamCaching property.
     * 
     * @param value
     *     allowed object is
     *     {@link CamelStreamCachingStrategyDefinition }
     *     
     */
    public void setStreamCaching(CamelStreamCachingStrategyDefinition value) {
        this.streamCaching = value;
    }

    /**
     * Gets the value of the templateOrConsumerTemplateOrProxy property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the templateOrConsumerTemplateOrProxy property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTemplateOrConsumerTemplateOrProxy().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CamelProducerTemplateFactoryBean }
     * {@link CamelConsumerTemplateFactoryBean }
     * {@link Object }
     * {@link CamelServiceExporterDefinition }
     * {@link CamelErrorHandlerFactoryBean }
     * 
     * 
     */
    public List<Object> getTemplateOrConsumerTemplateOrProxy() {
        if (templateOrConsumerTemplateOrProxy == null) {
            templateOrConsumerTemplateOrProxy = new ArrayList<Object>();
        }
        return this.templateOrConsumerTemplateOrProxy;
    }

    /**
     * Gets the value of the routeBuilder property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the routeBuilder property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRouteBuilder().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RouteBuilderDefinition }
     * 
     * 
     */
    public List<RouteBuilderDefinition> getRouteBuilder() {
        if (routeBuilder == null) {
            routeBuilder = new ArrayList<RouteBuilderDefinition>();
        }
        return this.routeBuilder;
    }

    /**
     * Gets the value of the routeContextRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the routeContextRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRouteContextRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RouteContextRefDefinition }
     * 
     * 
     */
    public List<RouteContextRefDefinition> getRouteContextRef() {
        if (routeContextRef == null) {
            routeContextRef = new ArrayList<RouteContextRefDefinition>();
        }
        return this.routeContextRef;
    }

    /**
     * Gets the value of the restContextRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the restContextRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRestContextRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RestContextRefDefinition }
     * 
     * 
     */
    public List<RestContextRefDefinition> getRestContextRef() {
        if (restContextRef == null) {
            restContextRef = new ArrayList<RestContextRefDefinition>();
        }
        return this.restContextRef;
    }

    /**
     * Gets the value of the threadPoolProfile property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the threadPoolProfile property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getThreadPoolProfile().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ThreadPoolProfileDefinition }
     * 
     * 
     */
    public List<ThreadPoolProfileDefinition> getThreadPoolProfile() {
        if (threadPoolProfile == null) {
            threadPoolProfile = new ArrayList<ThreadPoolProfileDefinition>();
        }
        return this.threadPoolProfile;
    }

    /**
     * Gets the value of the threadPool property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the threadPool property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getThreadPool().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CamelThreadPoolFactoryBean }
     * 
     * 
     */
    public List<CamelThreadPoolFactoryBean> getThreadPool() {
        if (threadPool == null) {
            threadPool = new ArrayList<CamelThreadPoolFactoryBean>();
        }
        return this.threadPool;
    }

    /**
     * Gets the value of the endpoint property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the endpoint property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEndpoint().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CamelEndpointFactoryBean }
     * 
     * 
     */
    public List<CamelEndpointFactoryBean> getEndpoint() {
        if (endpoint == null) {
            endpoint = new ArrayList<CamelEndpointFactoryBean>();
        }
        return this.endpoint;
    }

    /**
     * Gets the value of the dataFormats property.
     * 
     * @return
     *     possible object is
     *     {@link DataFormatsDefinition }
     *     
     */
    public DataFormatsDefinition getDataFormats() {
        return dataFormats;
    }

    /**
     * Sets the value of the dataFormats property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataFormatsDefinition }
     *     
     */
    public void setDataFormats(DataFormatsDefinition value) {
        this.dataFormats = value;
    }

    /**
     * Gets the value of the redeliveryPolicyProfile property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the redeliveryPolicyProfile property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRedeliveryPolicyProfile().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CamelRedeliveryPolicyFactoryBean }
     * 
     * 
     */
    public List<CamelRedeliveryPolicyFactoryBean> getRedeliveryPolicyProfile() {
        if (redeliveryPolicyProfile == null) {
            redeliveryPolicyProfile = new ArrayList<CamelRedeliveryPolicyFactoryBean>();
        }
        return this.redeliveryPolicyProfile;
    }

    /**
     * Gets the value of the onException property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the onException property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOnException().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OnExceptionDefinition }
     * 
     * 
     */
    public List<OnExceptionDefinition> getOnException() {
        if (onException == null) {
            onException = new ArrayList<OnExceptionDefinition>();
        }
        return this.onException;
    }

    /**
     * Gets the value of the onCompletion property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the onCompletion property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOnCompletion().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OnCompletionDefinition }
     * 
     * 
     */
    public List<OnCompletionDefinition> getOnCompletion() {
        if (onCompletion == null) {
            onCompletion = new ArrayList<OnCompletionDefinition>();
        }
        return this.onCompletion;
    }

    /**
     * Gets the value of the intercept property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the intercept property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIntercept().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InterceptDefinition }
     * 
     * 
     */
    public List<InterceptDefinition> getIntercept() {
        if (intercept == null) {
            intercept = new ArrayList<InterceptDefinition>();
        }
        return this.intercept;
    }

    /**
     * Gets the value of the interceptFrom property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the interceptFrom property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInterceptFrom().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InterceptFromDefinition }
     * 
     * 
     */
    public List<InterceptFromDefinition> getInterceptFrom() {
        if (interceptFrom == null) {
            interceptFrom = new ArrayList<InterceptFromDefinition>();
        }
        return this.interceptFrom;
    }

    /**
     * Gets the value of the interceptSendToEndpoint property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the interceptSendToEndpoint property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInterceptSendToEndpoint().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InterceptSendToEndpointDefinition }
     * 
     * 
     */
    public List<InterceptSendToEndpointDefinition> getInterceptSendToEndpoint() {
        if (interceptSendToEndpoint == null) {
            interceptSendToEndpoint = new ArrayList<InterceptSendToEndpointDefinition>();
        }
        return this.interceptSendToEndpoint;
    }

    /**
     * Gets the value of the restConfiguration property.
     * 
     * @return
     *     possible object is
     *     {@link RestConfigurationDefinition }
     *     
     */
    public RestConfigurationDefinition getRestConfiguration() {
        return restConfiguration;
    }

    /**
     * Sets the value of the restConfiguration property.
     * 
     * @param value
     *     allowed object is
     *     {@link RestConfigurationDefinition }
     *     
     */
    public void setRestConfiguration(RestConfigurationDefinition value) {
        this.restConfiguration = value;
    }

    /**
     * Gets the value of the rest property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rest property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRest().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RestDefinition }
     * 
     * 
     */
    public List<RestDefinition> getRest() {
        if (rest == null) {
            rest = new ArrayList<RestDefinition>();
        }
        return this.rest;
    }

    /**
     * Gets the value of the route property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the route property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRoute().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RouteDefinition }
     * 
     * 
     */
    public List<RouteDefinition> getRoute() {
        if (route == null) {
            route = new ArrayList<RouteDefinition>();
        }
        return this.route;
    }

    /**
     * Gets the value of the dependsOn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDependsOn() {
        return dependsOn;
    }

    /**
     * Sets the value of the dependsOn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDependsOn(String value) {
        this.dependsOn = value;
    }

    /**
     * Gets the value of the trace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrace() {
        return trace;
    }

    /**
     * Sets the value of the trace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrace(String value) {
        this.trace = value;
    }

    /**
     * Gets the value of the messageHistory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageHistory() {
        return messageHistory;
    }

    /**
     * Sets the value of the messageHistory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageHistory(String value) {
        this.messageHistory = value;
    }

    /**
     * Gets the value of the streamCache property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStreamCache() {
        return streamCache;
    }

    /**
     * Sets the value of the streamCache property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStreamCache(String value) {
        this.streamCache = value;
    }

    /**
     * Gets the value of the delayer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDelayer() {
        return delayer;
    }

    /**
     * Sets the value of the delayer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDelayer(String value) {
        this.delayer = value;
    }

    /**
     * Gets the value of the handleFault property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHandleFault() {
        return handleFault;
    }

    /**
     * Sets the value of the handleFault property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHandleFault(String value) {
        this.handleFault = value;
    }

    /**
     * Gets the value of the errorHandlerRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getErrorHandlerRef() {
        return errorHandlerRef;
    }

    /**
     * Sets the value of the errorHandlerRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setErrorHandlerRef(String value) {
        this.errorHandlerRef = value;
    }

    /**
     * Gets the value of the autoStartup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAutoStartup() {
        return autoStartup;
    }

    /**
     * Sets the value of the autoStartup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAutoStartup(String value) {
        this.autoStartup = value;
    }

    /**
     * Gets the value of the useMDCLogging property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUseMDCLogging() {
        return useMDCLogging;
    }

    /**
     * Sets the value of the useMDCLogging property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUseMDCLogging(String value) {
        this.useMDCLogging = value;
    }

    /**
     * Gets the value of the useBreadcrumb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUseBreadcrumb() {
        return useBreadcrumb;
    }

    /**
     * Sets the value of the useBreadcrumb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUseBreadcrumb(String value) {
        this.useBreadcrumb = value;
    }

    /**
     * Gets the value of the allowUseOriginalMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAllowUseOriginalMessage() {
        return allowUseOriginalMessage;
    }

    /**
     * Sets the value of the allowUseOriginalMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAllowUseOriginalMessage(String value) {
        this.allowUseOriginalMessage = value;
    }

    /**
     * Gets the value of the runtimeEndpointRegistryEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRuntimeEndpointRegistryEnabled() {
        return runtimeEndpointRegistryEnabled;
    }

    /**
     * Sets the value of the runtimeEndpointRegistryEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRuntimeEndpointRegistryEnabled(String value) {
        this.runtimeEndpointRegistryEnabled = value;
    }

    /**
     * Gets the value of the managementNamePattern property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getManagementNamePattern() {
        return managementNamePattern;
    }

    /**
     * Sets the value of the managementNamePattern property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setManagementNamePattern(String value) {
        this.managementNamePattern = value;
    }

    /**
     * Gets the value of the threadNamePattern property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getThreadNamePattern() {
        return threadNamePattern;
    }

    /**
     * Sets the value of the threadNamePattern property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setThreadNamePattern(String value) {
        this.threadNamePattern = value;
    }

    /**
     * Gets the value of the useBlueprintPropertyResolver property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUseBlueprintPropertyResolver() {
        return useBlueprintPropertyResolver;
    }

    /**
     * Sets the value of the useBlueprintPropertyResolver property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUseBlueprintPropertyResolver(Boolean value) {
        this.useBlueprintPropertyResolver = value;
    }

    /**
     * Gets the value of the shutdownRoute property.
     * 
     * @return
     *     possible object is
     *     {@link ShutdownRoute }
     *     
     */
    public ShutdownRoute getShutdownRoute() {
        return shutdownRoute;
    }

    /**
     * Sets the value of the shutdownRoute property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShutdownRoute }
     *     
     */
    public void setShutdownRoute(ShutdownRoute value) {
        this.shutdownRoute = value;
    }

    /**
     * Gets the value of the shutdownRunningTask property.
     * 
     * @return
     *     possible object is
     *     {@link ShutdownRunningTask }
     *     
     */
    public ShutdownRunningTask getShutdownRunningTask() {
        return shutdownRunningTask;
    }

    /**
     * Sets the value of the shutdownRunningTask property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShutdownRunningTask }
     *     
     */
    public void setShutdownRunningTask(ShutdownRunningTask value) {
        this.shutdownRunningTask = value;
    }

    /**
     * Gets the value of the lazyLoadTypeConverters property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isLazyLoadTypeConverters() {
        return lazyLoadTypeConverters;
    }

    /**
     * Sets the value of the lazyLoadTypeConverters property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLazyLoadTypeConverters(Boolean value) {
        this.lazyLoadTypeConverters = value;
    }

    /**
     * Gets the value of the typeConverterStatisticsEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isTypeConverterStatisticsEnabled() {
        return typeConverterStatisticsEnabled;
    }

    /**
     * Sets the value of the typeConverterStatisticsEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTypeConverterStatisticsEnabled(Boolean value) {
        this.typeConverterStatisticsEnabled = value;
    }

}
