//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.13 at 12:09:41 PM EST 
//


package org.jboss.mapper.camel.blueprint;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for camelStreamCachingStrategyDefinition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="camelStreamCachingStrategyDefinition">
 *   &lt;complexContent>
 *     &lt;extension base="{http://camel.apache.org/schema/blueprint}identifiedType">
 *       &lt;sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="enabled" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="spoolDirectory" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="spoolChiper" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="spoolThreshold" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="spoolUsedHeapMemoryThreshold" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="spoolUsedHeapMemoryLimit" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="spoolRules" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="bufferSize" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="removeSpoolDirectoryWhenStopping" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="statisticsEnabled" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="anySpoolRules" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "camelStreamCachingStrategyDefinition")
public class CamelStreamCachingStrategyDefinition
    extends IdentifiedType
{

    @XmlAttribute(name = "enabled")
    protected String enabled;
    @XmlAttribute(name = "spoolDirectory")
    protected String spoolDirectory;
    @XmlAttribute(name = "spoolChiper")
    protected String spoolChiper;
    @XmlAttribute(name = "spoolThreshold")
    protected String spoolThreshold;
    @XmlAttribute(name = "spoolUsedHeapMemoryThreshold")
    protected String spoolUsedHeapMemoryThreshold;
    @XmlAttribute(name = "spoolUsedHeapMemoryLimit")
    protected String spoolUsedHeapMemoryLimit;
    @XmlAttribute(name = "spoolRules")
    protected String spoolRules;
    @XmlAttribute(name = "bufferSize")
    protected String bufferSize;
    @XmlAttribute(name = "removeSpoolDirectoryWhenStopping")
    protected String removeSpoolDirectoryWhenStopping;
    @XmlAttribute(name = "statisticsEnabled")
    protected String statisticsEnabled;
    @XmlAttribute(name = "anySpoolRules")
    protected String anySpoolRules;

    /**
     * Gets the value of the enabled property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnabled() {
        return enabled;
    }

    /**
     * Sets the value of the enabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnabled(String value) {
        this.enabled = value;
    }

    /**
     * Gets the value of the spoolDirectory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpoolDirectory() {
        return spoolDirectory;
    }

    /**
     * Sets the value of the spoolDirectory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpoolDirectory(String value) {
        this.spoolDirectory = value;
    }

    /**
     * Gets the value of the spoolChiper property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpoolChiper() {
        return spoolChiper;
    }

    /**
     * Sets the value of the spoolChiper property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpoolChiper(String value) {
        this.spoolChiper = value;
    }

    /**
     * Gets the value of the spoolThreshold property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpoolThreshold() {
        return spoolThreshold;
    }

    /**
     * Sets the value of the spoolThreshold property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpoolThreshold(String value) {
        this.spoolThreshold = value;
    }

    /**
     * Gets the value of the spoolUsedHeapMemoryThreshold property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpoolUsedHeapMemoryThreshold() {
        return spoolUsedHeapMemoryThreshold;
    }

    /**
     * Sets the value of the spoolUsedHeapMemoryThreshold property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpoolUsedHeapMemoryThreshold(String value) {
        this.spoolUsedHeapMemoryThreshold = value;
    }

    /**
     * Gets the value of the spoolUsedHeapMemoryLimit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpoolUsedHeapMemoryLimit() {
        return spoolUsedHeapMemoryLimit;
    }

    /**
     * Sets the value of the spoolUsedHeapMemoryLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpoolUsedHeapMemoryLimit(String value) {
        this.spoolUsedHeapMemoryLimit = value;
    }

    /**
     * Gets the value of the spoolRules property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpoolRules() {
        return spoolRules;
    }

    /**
     * Sets the value of the spoolRules property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpoolRules(String value) {
        this.spoolRules = value;
    }

    /**
     * Gets the value of the bufferSize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBufferSize() {
        return bufferSize;
    }

    /**
     * Sets the value of the bufferSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBufferSize(String value) {
        this.bufferSize = value;
    }

    /**
     * Gets the value of the removeSpoolDirectoryWhenStopping property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemoveSpoolDirectoryWhenStopping() {
        return removeSpoolDirectoryWhenStopping;
    }

    /**
     * Sets the value of the removeSpoolDirectoryWhenStopping property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemoveSpoolDirectoryWhenStopping(String value) {
        this.removeSpoolDirectoryWhenStopping = value;
    }

    /**
     * Gets the value of the statisticsEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatisticsEnabled() {
        return statisticsEnabled;
    }

    /**
     * Sets the value of the statisticsEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatisticsEnabled(String value) {
        this.statisticsEnabled = value;
    }

    /**
     * Gets the value of the anySpoolRules property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnySpoolRules() {
        return anySpoolRules;
    }

    /**
     * Sets the value of the anySpoolRules property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnySpoolRules(String value) {
        this.anySpoolRules = value;
    }

}
