//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.13 at 12:09:41 PM EST 
//


package org.jboss.mapper.camel.blueprint;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for expressionSubElementDefinition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="expressionSubElementDefinition">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{http://camel.apache.org/schema/blueprint}expressionDefinition"/>
 *         &lt;element ref="{http://camel.apache.org/schema/blueprint}constant"/>
 *         &lt;element ref="{http://camel.apache.org/schema/blueprint}el"/>
 *         &lt;element ref="{http://camel.apache.org/schema/blueprint}groovy"/>
 *         &lt;element ref="{http://camel.apache.org/schema/blueprint}header"/>
 *         &lt;element ref="{http://camel.apache.org/schema/blueprint}jxpath"/>
 *         &lt;element ref="{http://camel.apache.org/schema/blueprint}javaScript"/>
 *         &lt;element ref="{http://camel.apache.org/schema/blueprint}jsonpath"/>
 *         &lt;element ref="{http://camel.apache.org/schema/blueprint}language"/>
 *         &lt;element ref="{http://camel.apache.org/schema/blueprint}method"/>
 *         &lt;element ref="{http://camel.apache.org/schema/blueprint}mvel"/>
 *         &lt;element ref="{http://camel.apache.org/schema/blueprint}ognl"/>
 *         &lt;element ref="{http://camel.apache.org/schema/blueprint}php"/>
 *         &lt;element ref="{http://camel.apache.org/schema/blueprint}property"/>
 *         &lt;element ref="{http://camel.apache.org/schema/blueprint}python"/>
 *         &lt;element ref="{http://camel.apache.org/schema/blueprint}ref"/>
 *         &lt;element ref="{http://camel.apache.org/schema/blueprint}ruby"/>
 *         &lt;element ref="{http://camel.apache.org/schema/blueprint}simple"/>
 *         &lt;element ref="{http://camel.apache.org/schema/blueprint}spel"/>
 *         &lt;element ref="{http://camel.apache.org/schema/blueprint}sql"/>
 *         &lt;element ref="{http://camel.apache.org/schema/blueprint}tokenize"/>
 *         &lt;element ref="{http://camel.apache.org/schema/blueprint}vtdxml"/>
 *         &lt;element ref="{http://camel.apache.org/schema/blueprint}xtokenize"/>
 *         &lt;element ref="{http://camel.apache.org/schema/blueprint}xpath"/>
 *         &lt;element ref="{http://camel.apache.org/schema/blueprint}xquery"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "expressionSubElementDefinition", propOrder = {
    "expressionDefinition",
    "constant",
    "el",
    "groovy",
    "header",
    "jxpath",
    "javaScript",
    "jsonpath",
    "language",
    "method",
    "mvel",
    "ognl",
    "php",
    "property",
    "python",
    "ref",
    "ruby",
    "simple",
    "spel",
    "sql",
    "tokenize",
    "vtdxml",
    "xtokenize",
    "xpath",
    "xquery"
})
public class ExpressionSubElementDefinition {

    protected Expression expressionDefinition;
    protected ConstantExpression constant;
    protected ElExpression el;
    protected GroovyExpression groovy;
    protected HeaderExpression header;
    protected JxPathExpression jxpath;
    protected JavaScriptExpression javaScript;
    protected JsonPathExpression jsonpath;
    protected LanguageExpression language;
    protected MethodCallExpression method;
    protected MvelExpression mvel;
    protected OgnlExpression ognl;
    protected PhpExpression php;
    @XmlElement(nillable = true)
    protected Object property;
    protected PythonExpression python;
    protected RefExpression ref;
    protected RubyExpression ruby;
    protected SimpleExpression simple;
    protected SpELExpression spel;
    protected SqlExpression sql;
    protected TokenizerExpression tokenize;
    protected VtdXmlExpression vtdxml;
    protected XmlTokenizerExpression xtokenize;
    protected XPathExpression xpath;
    protected XQueryExpression xquery;

    /**
     * Gets the value of the expressionDefinition property.
     * 
     * @return
     *     possible object is
     *     {@link Expression }
     *     
     */
    public Expression getExpressionDefinition() {
        return expressionDefinition;
    }

    /**
     * Sets the value of the expressionDefinition property.
     * 
     * @param value
     *     allowed object is
     *     {@link Expression }
     *     
     */
    public void setExpressionDefinition(Expression value) {
        this.expressionDefinition = value;
    }

    /**
     * Gets the value of the constant property.
     * 
     * @return
     *     possible object is
     *     {@link ConstantExpression }
     *     
     */
    public ConstantExpression getConstant() {
        return constant;
    }

    /**
     * Sets the value of the constant property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConstantExpression }
     *     
     */
    public void setConstant(ConstantExpression value) {
        this.constant = value;
    }

    /**
     * Gets the value of the el property.
     * 
     * @return
     *     possible object is
     *     {@link ElExpression }
     *     
     */
    public ElExpression getEl() {
        return el;
    }

    /**
     * Sets the value of the el property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElExpression }
     *     
     */
    public void setEl(ElExpression value) {
        this.el = value;
    }

    /**
     * Gets the value of the groovy property.
     * 
     * @return
     *     possible object is
     *     {@link GroovyExpression }
     *     
     */
    public GroovyExpression getGroovy() {
        return groovy;
    }

    /**
     * Sets the value of the groovy property.
     * 
     * @param value
     *     allowed object is
     *     {@link GroovyExpression }
     *     
     */
    public void setGroovy(GroovyExpression value) {
        this.groovy = value;
    }

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link HeaderExpression }
     *     
     */
    public HeaderExpression getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link HeaderExpression }
     *     
     */
    public void setHeader(HeaderExpression value) {
        this.header = value;
    }

    /**
     * Gets the value of the jxpath property.
     * 
     * @return
     *     possible object is
     *     {@link JxPathExpression }
     *     
     */
    public JxPathExpression getJxpath() {
        return jxpath;
    }

    /**
     * Sets the value of the jxpath property.
     * 
     * @param value
     *     allowed object is
     *     {@link JxPathExpression }
     *     
     */
    public void setJxpath(JxPathExpression value) {
        this.jxpath = value;
    }

    /**
     * Gets the value of the javaScript property.
     * 
     * @return
     *     possible object is
     *     {@link JavaScriptExpression }
     *     
     */
    public JavaScriptExpression getJavaScript() {
        return javaScript;
    }

    /**
     * Sets the value of the javaScript property.
     * 
     * @param value
     *     allowed object is
     *     {@link JavaScriptExpression }
     *     
     */
    public void setJavaScript(JavaScriptExpression value) {
        this.javaScript = value;
    }

    /**
     * Gets the value of the jsonpath property.
     * 
     * @return
     *     possible object is
     *     {@link JsonPathExpression }
     *     
     */
    public JsonPathExpression getJsonpath() {
        return jsonpath;
    }

    /**
     * Sets the value of the jsonpath property.
     * 
     * @param value
     *     allowed object is
     *     {@link JsonPathExpression }
     *     
     */
    public void setJsonpath(JsonPathExpression value) {
        this.jsonpath = value;
    }

    /**
     * Gets the value of the language property.
     * 
     * @return
     *     possible object is
     *     {@link LanguageExpression }
     *     
     */
    public LanguageExpression getLanguage() {
        return language;
    }

    /**
     * Sets the value of the language property.
     * 
     * @param value
     *     allowed object is
     *     {@link LanguageExpression }
     *     
     */
    public void setLanguage(LanguageExpression value) {
        this.language = value;
    }

    /**
     * Gets the value of the method property.
     * 
     * @return
     *     possible object is
     *     {@link MethodCallExpression }
     *     
     */
    public MethodCallExpression getMethod() {
        return method;
    }

    /**
     * Sets the value of the method property.
     * 
     * @param value
     *     allowed object is
     *     {@link MethodCallExpression }
     *     
     */
    public void setMethod(MethodCallExpression value) {
        this.method = value;
    }

    /**
     * Gets the value of the mvel property.
     * 
     * @return
     *     possible object is
     *     {@link MvelExpression }
     *     
     */
    public MvelExpression getMvel() {
        return mvel;
    }

    /**
     * Sets the value of the mvel property.
     * 
     * @param value
     *     allowed object is
     *     {@link MvelExpression }
     *     
     */
    public void setMvel(MvelExpression value) {
        this.mvel = value;
    }

    /**
     * Gets the value of the ognl property.
     * 
     * @return
     *     possible object is
     *     {@link OgnlExpression }
     *     
     */
    public OgnlExpression getOgnl() {
        return ognl;
    }

    /**
     * Sets the value of the ognl property.
     * 
     * @param value
     *     allowed object is
     *     {@link OgnlExpression }
     *     
     */
    public void setOgnl(OgnlExpression value) {
        this.ognl = value;
    }

    /**
     * Gets the value of the php property.
     * 
     * @return
     *     possible object is
     *     {@link PhpExpression }
     *     
     */
    public PhpExpression getPhp() {
        return php;
    }

    /**
     * Sets the value of the php property.
     * 
     * @param value
     *     allowed object is
     *     {@link PhpExpression }
     *     
     */
    public void setPhp(PhpExpression value) {
        this.php = value;
    }

    /**
     * Gets the value of the property property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getProperty() {
        return property;
    }

    /**
     * Sets the value of the property property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setProperty(Object value) {
        this.property = value;
    }

    /**
     * Gets the value of the python property.
     * 
     * @return
     *     possible object is
     *     {@link PythonExpression }
     *     
     */
    public PythonExpression getPython() {
        return python;
    }

    /**
     * Sets the value of the python property.
     * 
     * @param value
     *     allowed object is
     *     {@link PythonExpression }
     *     
     */
    public void setPython(PythonExpression value) {
        this.python = value;
    }

    /**
     * Gets the value of the ref property.
     * 
     * @return
     *     possible object is
     *     {@link RefExpression }
     *     
     */
    public RefExpression getRef() {
        return ref;
    }

    /**
     * Sets the value of the ref property.
     * 
     * @param value
     *     allowed object is
     *     {@link RefExpression }
     *     
     */
    public void setRef(RefExpression value) {
        this.ref = value;
    }

    /**
     * Gets the value of the ruby property.
     * 
     * @return
     *     possible object is
     *     {@link RubyExpression }
     *     
     */
    public RubyExpression getRuby() {
        return ruby;
    }

    /**
     * Sets the value of the ruby property.
     * 
     * @param value
     *     allowed object is
     *     {@link RubyExpression }
     *     
     */
    public void setRuby(RubyExpression value) {
        this.ruby = value;
    }

    /**
     * Gets the value of the simple property.
     * 
     * @return
     *     possible object is
     *     {@link SimpleExpression }
     *     
     */
    public SimpleExpression getSimple() {
        return simple;
    }

    /**
     * Sets the value of the simple property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimpleExpression }
     *     
     */
    public void setSimple(SimpleExpression value) {
        this.simple = value;
    }

    /**
     * Gets the value of the spel property.
     * 
     * @return
     *     possible object is
     *     {@link SpELExpression }
     *     
     */
    public SpELExpression getSpel() {
        return spel;
    }

    /**
     * Sets the value of the spel property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpELExpression }
     *     
     */
    public void setSpel(SpELExpression value) {
        this.spel = value;
    }

    /**
     * Gets the value of the sql property.
     * 
     * @return
     *     possible object is
     *     {@link SqlExpression }
     *     
     */
    public SqlExpression getSql() {
        return sql;
    }

    /**
     * Sets the value of the sql property.
     * 
     * @param value
     *     allowed object is
     *     {@link SqlExpression }
     *     
     */
    public void setSql(SqlExpression value) {
        this.sql = value;
    }

    /**
     * Gets the value of the tokenize property.
     * 
     * @return
     *     possible object is
     *     {@link TokenizerExpression }
     *     
     */
    public TokenizerExpression getTokenize() {
        return tokenize;
    }

    /**
     * Sets the value of the tokenize property.
     * 
     * @param value
     *     allowed object is
     *     {@link TokenizerExpression }
     *     
     */
    public void setTokenize(TokenizerExpression value) {
        this.tokenize = value;
    }

    /**
     * Gets the value of the vtdxml property.
     * 
     * @return
     *     possible object is
     *     {@link VtdXmlExpression }
     *     
     */
    public VtdXmlExpression getVtdxml() {
        return vtdxml;
    }

    /**
     * Sets the value of the vtdxml property.
     * 
     * @param value
     *     allowed object is
     *     {@link VtdXmlExpression }
     *     
     */
    public void setVtdxml(VtdXmlExpression value) {
        this.vtdxml = value;
    }

    /**
     * Gets the value of the xtokenize property.
     * 
     * @return
     *     possible object is
     *     {@link XmlTokenizerExpression }
     *     
     */
    public XmlTokenizerExpression getXtokenize() {
        return xtokenize;
    }

    /**
     * Sets the value of the xtokenize property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlTokenizerExpression }
     *     
     */
    public void setXtokenize(XmlTokenizerExpression value) {
        this.xtokenize = value;
    }

    /**
     * Gets the value of the xpath property.
     * 
     * @return
     *     possible object is
     *     {@link XPathExpression }
     *     
     */
    public XPathExpression getXpath() {
        return xpath;
    }

    /**
     * Sets the value of the xpath property.
     * 
     * @param value
     *     allowed object is
     *     {@link XPathExpression }
     *     
     */
    public void setXpath(XPathExpression value) {
        this.xpath = value;
    }

    /**
     * Gets the value of the xquery property.
     * 
     * @return
     *     possible object is
     *     {@link XQueryExpression }
     *     
     */
    public XQueryExpression getXquery() {
        return xquery;
    }

    /**
     * Sets the value of the xquery property.
     * 
     * @param value
     *     allowed object is
     *     {@link XQueryExpression }
     *     
     */
    public void setXquery(XQueryExpression value) {
        this.xquery = value;
    }

}
