//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.13 at 12:09:41 PM EST 
//


package org.jboss.mapper.camel.blueprint;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for marshalDefinition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="marshalDefinition">
 *   &lt;complexContent>
 *     &lt;extension base="{http://camel.apache.org/schema/blueprint}noOutputDefinition">
 *       &lt;sequence>
 *         &lt;choice minOccurs="0">
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}avro"/>
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}base64"/>
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}beanio"/>
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}bindy"/>
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}castor"/>
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}crypto"/>
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}csv"/>
 *           &lt;element name="custom" type="{http://camel.apache.org/schema/blueprint}customDataFormat"/>
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}flatpack"/>
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}gzip"/>
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}hl7"/>
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}jaxb"/>
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}jibx"/>
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}json"/>
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}protobuf"/>
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}rss"/>
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}secureXML"/>
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}serialization"/>
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}soapjaxb"/>
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}string"/>
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}syslog"/>
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}tidyMarkup"/>
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}xmlBeans"/>
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}xmljson"/>
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}xmlrpc"/>
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}xstream"/>
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}pgp"/>
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}zip"/>
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}zipFile"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="ref" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;anyAttribute processContents='skip' namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "marshalDefinition", propOrder = {
    "avro",
    "base64",
    "beanio",
    "bindy",
    "castor",
    "crypto",
    "csv",
    "custom",
    "flatpack",
    "gzip",
    "hl7",
    "jaxb",
    "jibx",
    "json",
    "protobuf",
    "rss",
    "secureXML",
    "serialization",
    "soapjaxb",
    "string",
    "syslog",
    "tidyMarkup",
    "xmlBeans",
    "xmljson",
    "xmlrpc",
    "xstream",
    "pgp",
    "zip",
    "zipFile"
})
public class MarshalDefinition
    extends NoOutputDefinition
{

    protected AvroDataFormat avro;
    protected Base64DataFormat base64;
    protected BeanioDataFormat beanio;
    protected BindyDataFormat bindy;
    protected CastorDataFormat castor;
    protected CryptoDataFormat crypto;
    protected CsvDataFormat csv;
    protected CustomDataFormat custom;
    protected FlatpackDataFormat flatpack;
    protected GzipDataFormat gzip;
    protected Hl7DataFormat hl7;
    protected JaxbDataFormat jaxb;
    protected JibxDataFormat jibx;
    protected JsonDataFormat json;
    protected ProtobufDataFormat protobuf;
    protected RssDataFormat rss;
    protected XmlSecurityDataFormat secureXML;
    protected SerializationDataFormat serialization;
    protected SoapJaxbDataFormat soapjaxb;
    protected StringDataFormat string;
    protected SyslogDataFormat syslog;
    protected TidyMarkupDataFormat tidyMarkup;
    protected XmlBeansDataFormat xmlBeans;
    protected XmlJsonDataFormat xmljson;
    protected XmlRpcDataFormat xmlrpc;
    protected XStreamDataFormat xstream;
    protected PgpDataFormat pgp;
    protected ZipDataFormat zip;
    protected ZipFileDataFormat zipFile;
    @XmlAttribute(name = "ref")
    protected String ref;

    /**
     * Gets the value of the avro property.
     * 
     * @return
     *     possible object is
     *     {@link AvroDataFormat }
     *     
     */
    public AvroDataFormat getAvro() {
        return avro;
    }

    /**
     * Sets the value of the avro property.
     * 
     * @param value
     *     allowed object is
     *     {@link AvroDataFormat }
     *     
     */
    public void setAvro(AvroDataFormat value) {
        this.avro = value;
    }

    /**
     * Gets the value of the base64 property.
     * 
     * @return
     *     possible object is
     *     {@link Base64DataFormat }
     *     
     */
    public Base64DataFormat getBase64() {
        return base64;
    }

    /**
     * Sets the value of the base64 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Base64DataFormat }
     *     
     */
    public void setBase64(Base64DataFormat value) {
        this.base64 = value;
    }

    /**
     * Gets the value of the beanio property.
     * 
     * @return
     *     possible object is
     *     {@link BeanioDataFormat }
     *     
     */
    public BeanioDataFormat getBeanio() {
        return beanio;
    }

    /**
     * Sets the value of the beanio property.
     * 
     * @param value
     *     allowed object is
     *     {@link BeanioDataFormat }
     *     
     */
    public void setBeanio(BeanioDataFormat value) {
        this.beanio = value;
    }

    /**
     * Gets the value of the bindy property.
     * 
     * @return
     *     possible object is
     *     {@link BindyDataFormat }
     *     
     */
    public BindyDataFormat getBindy() {
        return bindy;
    }

    /**
     * Sets the value of the bindy property.
     * 
     * @param value
     *     allowed object is
     *     {@link BindyDataFormat }
     *     
     */
    public void setBindy(BindyDataFormat value) {
        this.bindy = value;
    }

    /**
     * Gets the value of the castor property.
     * 
     * @return
     *     possible object is
     *     {@link CastorDataFormat }
     *     
     */
    public CastorDataFormat getCastor() {
        return castor;
    }

    /**
     * Sets the value of the castor property.
     * 
     * @param value
     *     allowed object is
     *     {@link CastorDataFormat }
     *     
     */
    public void setCastor(CastorDataFormat value) {
        this.castor = value;
    }

    /**
     * Gets the value of the crypto property.
     * 
     * @return
     *     possible object is
     *     {@link CryptoDataFormat }
     *     
     */
    public CryptoDataFormat getCrypto() {
        return crypto;
    }

    /**
     * Sets the value of the crypto property.
     * 
     * @param value
     *     allowed object is
     *     {@link CryptoDataFormat }
     *     
     */
    public void setCrypto(CryptoDataFormat value) {
        this.crypto = value;
    }

    /**
     * Gets the value of the csv property.
     * 
     * @return
     *     possible object is
     *     {@link CsvDataFormat }
     *     
     */
    public CsvDataFormat getCsv() {
        return csv;
    }

    /**
     * Sets the value of the csv property.
     * 
     * @param value
     *     allowed object is
     *     {@link CsvDataFormat }
     *     
     */
    public void setCsv(CsvDataFormat value) {
        this.csv = value;
    }

    /**
     * Gets the value of the custom property.
     * 
     * @return
     *     possible object is
     *     {@link CustomDataFormat }
     *     
     */
    public CustomDataFormat getCustom() {
        return custom;
    }

    /**
     * Sets the value of the custom property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomDataFormat }
     *     
     */
    public void setCustom(CustomDataFormat value) {
        this.custom = value;
    }

    /**
     * Gets the value of the flatpack property.
     * 
     * @return
     *     possible object is
     *     {@link FlatpackDataFormat }
     *     
     */
    public FlatpackDataFormat getFlatpack() {
        return flatpack;
    }

    /**
     * Sets the value of the flatpack property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlatpackDataFormat }
     *     
     */
    public void setFlatpack(FlatpackDataFormat value) {
        this.flatpack = value;
    }

    /**
     * Gets the value of the gzip property.
     * 
     * @return
     *     possible object is
     *     {@link GzipDataFormat }
     *     
     */
    public GzipDataFormat getGzip() {
        return gzip;
    }

    /**
     * Sets the value of the gzip property.
     * 
     * @param value
     *     allowed object is
     *     {@link GzipDataFormat }
     *     
     */
    public void setGzip(GzipDataFormat value) {
        this.gzip = value;
    }

    /**
     * Gets the value of the hl7 property.
     * 
     * @return
     *     possible object is
     *     {@link Hl7DataFormat }
     *     
     */
    public Hl7DataFormat getHl7() {
        return hl7;
    }

    /**
     * Sets the value of the hl7 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Hl7DataFormat }
     *     
     */
    public void setHl7(Hl7DataFormat value) {
        this.hl7 = value;
    }

    /**
     * Gets the value of the jaxb property.
     * 
     * @return
     *     possible object is
     *     {@link JaxbDataFormat }
     *     
     */
    public JaxbDataFormat getJaxb() {
        return jaxb;
    }

    /**
     * Sets the value of the jaxb property.
     * 
     * @param value
     *     allowed object is
     *     {@link JaxbDataFormat }
     *     
     */
    public void setJaxb(JaxbDataFormat value) {
        this.jaxb = value;
    }

    /**
     * Gets the value of the jibx property.
     * 
     * @return
     *     possible object is
     *     {@link JibxDataFormat }
     *     
     */
    public JibxDataFormat getJibx() {
        return jibx;
    }

    /**
     * Sets the value of the jibx property.
     * 
     * @param value
     *     allowed object is
     *     {@link JibxDataFormat }
     *     
     */
    public void setJibx(JibxDataFormat value) {
        this.jibx = value;
    }

    /**
     * Gets the value of the json property.
     * 
     * @return
     *     possible object is
     *     {@link JsonDataFormat }
     *     
     */
    public JsonDataFormat getJson() {
        return json;
    }

    /**
     * Sets the value of the json property.
     * 
     * @param value
     *     allowed object is
     *     {@link JsonDataFormat }
     *     
     */
    public void setJson(JsonDataFormat value) {
        this.json = value;
    }

    /**
     * Gets the value of the protobuf property.
     * 
     * @return
     *     possible object is
     *     {@link ProtobufDataFormat }
     *     
     */
    public ProtobufDataFormat getProtobuf() {
        return protobuf;
    }

    /**
     * Sets the value of the protobuf property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProtobufDataFormat }
     *     
     */
    public void setProtobuf(ProtobufDataFormat value) {
        this.protobuf = value;
    }

    /**
     * Gets the value of the rss property.
     * 
     * @return
     *     possible object is
     *     {@link RssDataFormat }
     *     
     */
    public RssDataFormat getRss() {
        return rss;
    }

    /**
     * Sets the value of the rss property.
     * 
     * @param value
     *     allowed object is
     *     {@link RssDataFormat }
     *     
     */
    public void setRss(RssDataFormat value) {
        this.rss = value;
    }

    /**
     * Gets the value of the secureXML property.
     * 
     * @return
     *     possible object is
     *     {@link XmlSecurityDataFormat }
     *     
     */
    public XmlSecurityDataFormat getSecureXML() {
        return secureXML;
    }

    /**
     * Sets the value of the secureXML property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlSecurityDataFormat }
     *     
     */
    public void setSecureXML(XmlSecurityDataFormat value) {
        this.secureXML = value;
    }

    /**
     * Gets the value of the serialization property.
     * 
     * @return
     *     possible object is
     *     {@link SerializationDataFormat }
     *     
     */
    public SerializationDataFormat getSerialization() {
        return serialization;
    }

    /**
     * Sets the value of the serialization property.
     * 
     * @param value
     *     allowed object is
     *     {@link SerializationDataFormat }
     *     
     */
    public void setSerialization(SerializationDataFormat value) {
        this.serialization = value;
    }

    /**
     * Gets the value of the soapjaxb property.
     * 
     * @return
     *     possible object is
     *     {@link SoapJaxbDataFormat }
     *     
     */
    public SoapJaxbDataFormat getSoapjaxb() {
        return soapjaxb;
    }

    /**
     * Sets the value of the soapjaxb property.
     * 
     * @param value
     *     allowed object is
     *     {@link SoapJaxbDataFormat }
     *     
     */
    public void setSoapjaxb(SoapJaxbDataFormat value) {
        this.soapjaxb = value;
    }

    /**
     * Gets the value of the string property.
     * 
     * @return
     *     possible object is
     *     {@link StringDataFormat }
     *     
     */
    public StringDataFormat getString() {
        return string;
    }

    /**
     * Sets the value of the string property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringDataFormat }
     *     
     */
    public void setString(StringDataFormat value) {
        this.string = value;
    }

    /**
     * Gets the value of the syslog property.
     * 
     * @return
     *     possible object is
     *     {@link SyslogDataFormat }
     *     
     */
    public SyslogDataFormat getSyslog() {
        return syslog;
    }

    /**
     * Sets the value of the syslog property.
     * 
     * @param value
     *     allowed object is
     *     {@link SyslogDataFormat }
     *     
     */
    public void setSyslog(SyslogDataFormat value) {
        this.syslog = value;
    }

    /**
     * Gets the value of the tidyMarkup property.
     * 
     * @return
     *     possible object is
     *     {@link TidyMarkupDataFormat }
     *     
     */
    public TidyMarkupDataFormat getTidyMarkup() {
        return tidyMarkup;
    }

    /**
     * Sets the value of the tidyMarkup property.
     * 
     * @param value
     *     allowed object is
     *     {@link TidyMarkupDataFormat }
     *     
     */
    public void setTidyMarkup(TidyMarkupDataFormat value) {
        this.tidyMarkup = value;
    }

    /**
     * Gets the value of the xmlBeans property.
     * 
     * @return
     *     possible object is
     *     {@link XmlBeansDataFormat }
     *     
     */
    public XmlBeansDataFormat getXmlBeans() {
        return xmlBeans;
    }

    /**
     * Sets the value of the xmlBeans property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlBeansDataFormat }
     *     
     */
    public void setXmlBeans(XmlBeansDataFormat value) {
        this.xmlBeans = value;
    }

    /**
     * Gets the value of the xmljson property.
     * 
     * @return
     *     possible object is
     *     {@link XmlJsonDataFormat }
     *     
     */
    public XmlJsonDataFormat getXmljson() {
        return xmljson;
    }

    /**
     * Sets the value of the xmljson property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlJsonDataFormat }
     *     
     */
    public void setXmljson(XmlJsonDataFormat value) {
        this.xmljson = value;
    }

    /**
     * Gets the value of the xmlrpc property.
     * 
     * @return
     *     possible object is
     *     {@link XmlRpcDataFormat }
     *     
     */
    public XmlRpcDataFormat getXmlrpc() {
        return xmlrpc;
    }

    /**
     * Sets the value of the xmlrpc property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlRpcDataFormat }
     *     
     */
    public void setXmlrpc(XmlRpcDataFormat value) {
        this.xmlrpc = value;
    }

    /**
     * Gets the value of the xstream property.
     * 
     * @return
     *     possible object is
     *     {@link XStreamDataFormat }
     *     
     */
    public XStreamDataFormat getXstream() {
        return xstream;
    }

    /**
     * Sets the value of the xstream property.
     * 
     * @param value
     *     allowed object is
     *     {@link XStreamDataFormat }
     *     
     */
    public void setXstream(XStreamDataFormat value) {
        this.xstream = value;
    }

    /**
     * Gets the value of the pgp property.
     * 
     * @return
     *     possible object is
     *     {@link PgpDataFormat }
     *     
     */
    public PgpDataFormat getPgp() {
        return pgp;
    }

    /**
     * Sets the value of the pgp property.
     * 
     * @param value
     *     allowed object is
     *     {@link PgpDataFormat }
     *     
     */
    public void setPgp(PgpDataFormat value) {
        this.pgp = value;
    }

    /**
     * Gets the value of the zip property.
     * 
     * @return
     *     possible object is
     *     {@link ZipDataFormat }
     *     
     */
    public ZipDataFormat getZip() {
        return zip;
    }

    /**
     * Sets the value of the zip property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZipDataFormat }
     *     
     */
    public void setZip(ZipDataFormat value) {
        this.zip = value;
    }

    /**
     * Gets the value of the zipFile property.
     * 
     * @return
     *     possible object is
     *     {@link ZipFileDataFormat }
     *     
     */
    public ZipFileDataFormat getZipFile() {
        return zipFile;
    }

    /**
     * Sets the value of the zipFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZipFileDataFormat }
     *     
     */
    public void setZipFile(ZipFileDataFormat value) {
        this.zipFile = value;
    }

    /**
     * Gets the value of the ref property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRef() {
        return ref;
    }

    /**
     * Sets the value of the ref property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRef(String value) {
        this.ref = value;
    }

}
