//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.13 at 12:09:41 PM EST 
//


package org.jboss.mapper.camel.blueprint;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for onCompletionDefinition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="onCompletionDefinition">
 *   &lt;complexContent>
 *     &lt;extension base="{http://camel.apache.org/schema/blueprint}processorDefinition">
 *       &lt;sequence>
 *         &lt;element name="onWhen" type="{http://camel.apache.org/schema/blueprint}whenDefinition" minOccurs="0"/>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}onException"/>
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}when"/>
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}onCompletion"/>
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}intercept"/>
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}interceptFrom"/>
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}interceptToEndpoint"/>
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}to"/>
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}route"/>
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}aop"/>
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}aggregate"/>
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}bean"/>
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}doCatch"/>
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}choice"/>
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}otherwise"/>
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}convertBodyTo"/>
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}delay"/>
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}dynamicRouter"/>
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}enrich"/>
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}filter"/>
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}doFinally"/>
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}idempotentConsumer"/>
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}inOnly"/>
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}inOut"/>
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}loadBalance"/>
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}log"/>
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}loop"/>
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}marshal"/>
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}multicast"/>
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}pipeline"/>
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}policy"/>
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}pollEnrich"/>
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}process"/>
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}recipientList"/>
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}removeHeader"/>
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}removeHeaders"/>
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}removeProperty"/>
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}resequence"/>
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}rollback"/>
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}routingSlip"/>
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}sample"/>
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}setBody"/>
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}setExchangePattern"/>
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}setFaultBody"/>
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}setHeader"/>
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}setOutHeader"/>
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}setProperty"/>
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}sort"/>
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}split"/>
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}stop"/>
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}threads"/>
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}throttle"/>
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}throwException"/>
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}transacted"/>
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}transform"/>
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}doTry"/>
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}unmarshal"/>
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}validate"/>
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}wireTap"/>
 *           &lt;element ref="{http://camel.apache.org/schema/blueprint}restBinding"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="mode" type="{http://camel.apache.org/schema/blueprint}onCompletionMode" />
 *       &lt;attribute name="onCompleteOnly" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="onFailureOnly" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="parallelProcessing" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="executorServiceRef" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="useOriginalMessage" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;anyAttribute processContents='skip' namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "onCompletionDefinition", propOrder = {
    "onWhen",
    "onExceptionOrWhenOrOnCompletion"
})
public class OnCompletionDefinition
    extends ProcessorDefinition
{

    protected WhenDefinition onWhen;
    @XmlElements({
        @XmlElement(name = "onException", type = OnExceptionDefinition.class),
        @XmlElement(name = "when", type = WhenDefinition.class),
        @XmlElement(name = "onCompletion", type = OnCompletionDefinition.class),
        @XmlElement(name = "intercept", type = InterceptDefinition.class),
        @XmlElement(name = "interceptFrom", type = InterceptFromDefinition.class),
        @XmlElement(name = "interceptToEndpoint", type = InterceptSendToEndpointDefinition.class),
        @XmlElement(name = "to", type = ToDefinition.class),
        @XmlElement(name = "route", type = RouteDefinition.class),
        @XmlElement(name = "aop", type = AopDefinition.class),
        @XmlElement(name = "aggregate", type = AggregateDefinition.class),
        @XmlElement(name = "bean", type = BeanDefinition.class),
        @XmlElement(name = "doCatch", type = CatchDefinition.class),
        @XmlElement(name = "choice", type = ChoiceDefinition.class),
        @XmlElement(name = "otherwise", type = OtherwiseDefinition.class),
        @XmlElement(name = "convertBodyTo", type = ConvertBodyDefinition.class),
        @XmlElement(name = "delay", type = DelayDefinition.class),
        @XmlElement(name = "dynamicRouter", type = DynamicRouterDefinition.class),
        @XmlElement(name = "enrich", type = EnrichDefinition.class),
        @XmlElement(name = "filter", type = FilterDefinition.class),
        @XmlElement(name = "doFinally", type = FinallyDefinition.class),
        @XmlElement(name = "idempotentConsumer", type = IdempotentConsumerDefinition.class),
        @XmlElement(name = "inOnly", type = InOnlyDefinition.class),
        @XmlElement(name = "inOut", type = InOutDefinition.class),
        @XmlElement(name = "loadBalance", type = LoadBalanceDefinition.class),
        @XmlElement(name = "log", type = LogDefinition.class),
        @XmlElement(name = "loop", type = LoopDefinition.class),
        @XmlElement(name = "marshal", type = MarshalDefinition.class),
        @XmlElement(name = "multicast", type = MulticastDefinition.class),
        @XmlElement(name = "pipeline", type = PipelineDefinition.class),
        @XmlElement(name = "policy", type = PolicyDefinition.class),
        @XmlElement(name = "pollEnrich", type = PollEnrichDefinition.class),
        @XmlElement(name = "process", type = ProcessDefinition.class),
        @XmlElement(name = "recipientList", type = RecipientListDefinition.class),
        @XmlElement(name = "removeHeader", type = RemoveHeaderDefinition.class),
        @XmlElement(name = "removeHeaders", type = RemoveHeadersDefinition.class),
        @XmlElement(name = "removeProperty", type = RemovePropertyDefinition.class),
        @XmlElement(name = "resequence", type = ResequenceDefinition.class),
        @XmlElement(name = "rollback", type = RollbackDefinition.class),
        @XmlElement(name = "routingSlip", type = RoutingSlipDefinition.class),
        @XmlElement(name = "sample", type = SamplingDefinition.class),
        @XmlElement(name = "setBody", type = SetBodyDefinition.class),
        @XmlElement(name = "setExchangePattern", type = SetExchangePatternDefinition.class),
        @XmlElement(name = "setFaultBody", type = SetFaultBodyDefinition.class),
        @XmlElement(name = "setHeader", type = SetHeaderDefinition.class),
        @XmlElement(name = "setOutHeader", type = SetOutHeaderDefinition.class),
        @XmlElement(name = "setProperty", type = SetPropertyDefinition.class),
        @XmlElement(name = "sort", type = SortDefinition.class),
        @XmlElement(name = "split", type = SplitDefinition.class),
        @XmlElement(name = "stop", type = StopDefinition.class),
        @XmlElement(name = "threads", type = ThreadsDefinition.class),
        @XmlElement(name = "throttle", type = ThrottleDefinition.class),
        @XmlElement(name = "throwException", type = ThrowExceptionDefinition.class),
        @XmlElement(name = "transacted", type = TransactedDefinition.class),
        @XmlElement(name = "transform", type = TransformDefinition.class),
        @XmlElement(name = "doTry", type = TryDefinition.class),
        @XmlElement(name = "unmarshal", type = UnmarshalDefinition.class),
        @XmlElement(name = "validate", type = ValidateDefinition.class),
        @XmlElement(name = "wireTap", type = WireTapDefinition.class),
        @XmlElement(name = "restBinding", type = RestBindingDefinition.class)
    })
    protected List<ProcessorDefinition> onExceptionOrWhenOrOnCompletion;
    @XmlAttribute(name = "mode")
    protected OnCompletionMode mode;
    @XmlAttribute(name = "onCompleteOnly")
    protected Boolean onCompleteOnly;
    @XmlAttribute(name = "onFailureOnly")
    protected Boolean onFailureOnly;
    @XmlAttribute(name = "parallelProcessing")
    protected Boolean parallelProcessing;
    @XmlAttribute(name = "executorServiceRef")
    protected String executorServiceRef;
    @XmlAttribute(name = "useOriginalMessage")
    protected Boolean useOriginalMessage;

    /**
     * Gets the value of the onWhen property.
     * 
     * @return
     *     possible object is
     *     {@link WhenDefinition }
     *     
     */
    public WhenDefinition getOnWhen() {
        return onWhen;
    }

    /**
     * Sets the value of the onWhen property.
     * 
     * @param value
     *     allowed object is
     *     {@link WhenDefinition }
     *     
     */
    public void setOnWhen(WhenDefinition value) {
        this.onWhen = value;
    }

    /**
     * Gets the value of the onExceptionOrWhenOrOnCompletion property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the onExceptionOrWhenOrOnCompletion property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOnExceptionOrWhenOrOnCompletion().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OnExceptionDefinition }
     * {@link WhenDefinition }
     * {@link OnCompletionDefinition }
     * {@link InterceptDefinition }
     * {@link InterceptFromDefinition }
     * {@link InterceptSendToEndpointDefinition }
     * {@link ToDefinition }
     * {@link RouteDefinition }
     * {@link AopDefinition }
     * {@link AggregateDefinition }
     * {@link BeanDefinition }
     * {@link CatchDefinition }
     * {@link ChoiceDefinition }
     * {@link OtherwiseDefinition }
     * {@link ConvertBodyDefinition }
     * {@link DelayDefinition }
     * {@link DynamicRouterDefinition }
     * {@link EnrichDefinition }
     * {@link FilterDefinition }
     * {@link FinallyDefinition }
     * {@link IdempotentConsumerDefinition }
     * {@link InOnlyDefinition }
     * {@link InOutDefinition }
     * {@link LoadBalanceDefinition }
     * {@link LogDefinition }
     * {@link LoopDefinition }
     * {@link MarshalDefinition }
     * {@link MulticastDefinition }
     * {@link PipelineDefinition }
     * {@link PolicyDefinition }
     * {@link PollEnrichDefinition }
     * {@link ProcessDefinition }
     * {@link RecipientListDefinition }
     * {@link RemoveHeaderDefinition }
     * {@link RemoveHeadersDefinition }
     * {@link RemovePropertyDefinition }
     * {@link ResequenceDefinition }
     * {@link RollbackDefinition }
     * {@link RoutingSlipDefinition }
     * {@link SamplingDefinition }
     * {@link SetBodyDefinition }
     * {@link SetExchangePatternDefinition }
     * {@link SetFaultBodyDefinition }
     * {@link SetHeaderDefinition }
     * {@link SetOutHeaderDefinition }
     * {@link SetPropertyDefinition }
     * {@link SortDefinition }
     * {@link SplitDefinition }
     * {@link StopDefinition }
     * {@link ThreadsDefinition }
     * {@link ThrottleDefinition }
     * {@link ThrowExceptionDefinition }
     * {@link TransactedDefinition }
     * {@link TransformDefinition }
     * {@link TryDefinition }
     * {@link UnmarshalDefinition }
     * {@link ValidateDefinition }
     * {@link WireTapDefinition }
     * {@link RestBindingDefinition }
     * 
     * 
     */
    public List<ProcessorDefinition> getOnExceptionOrWhenOrOnCompletion() {
        if (onExceptionOrWhenOrOnCompletion == null) {
            onExceptionOrWhenOrOnCompletion = new ArrayList<ProcessorDefinition>();
        }
        return this.onExceptionOrWhenOrOnCompletion;
    }

    /**
     * Gets the value of the mode property.
     * 
     * @return
     *     possible object is
     *     {@link OnCompletionMode }
     *     
     */
    public OnCompletionMode getMode() {
        return mode;
    }

    /**
     * Sets the value of the mode property.
     * 
     * @param value
     *     allowed object is
     *     {@link OnCompletionMode }
     *     
     */
    public void setMode(OnCompletionMode value) {
        this.mode = value;
    }

    /**
     * Gets the value of the onCompleteOnly property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isOnCompleteOnly() {
        return onCompleteOnly;
    }

    /**
     * Sets the value of the onCompleteOnly property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOnCompleteOnly(Boolean value) {
        this.onCompleteOnly = value;
    }

    /**
     * Gets the value of the onFailureOnly property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isOnFailureOnly() {
        return onFailureOnly;
    }

    /**
     * Sets the value of the onFailureOnly property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOnFailureOnly(Boolean value) {
        this.onFailureOnly = value;
    }

    /**
     * Gets the value of the parallelProcessing property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isParallelProcessing() {
        return parallelProcessing;
    }

    /**
     * Sets the value of the parallelProcessing property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setParallelProcessing(Boolean value) {
        this.parallelProcessing = value;
    }

    /**
     * Gets the value of the executorServiceRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExecutorServiceRef() {
        return executorServiceRef;
    }

    /**
     * Sets the value of the executorServiceRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExecutorServiceRef(String value) {
        this.executorServiceRef = value;
    }

    /**
     * Gets the value of the useOriginalMessage property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUseOriginalMessage() {
        return useOriginalMessage;
    }

    /**
     * Sets the value of the useOriginalMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUseOriginalMessage(Boolean value) {
        this.useOriginalMessage = value;
    }

}
