//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.13 at 12:09:41 PM EST 
//


package org.jboss.mapper.camel.blueprint;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for optimisticLockRetryPolicyDefinition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="optimisticLockRetryPolicyDefinition">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="maximumRetries" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="retryDelay" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="maximumRetryDelay" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="exponentialBackOff" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="randomBackOff" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "optimisticLockRetryPolicyDefinition")
public class OptimisticLockRetryPolicyDefinition {

    @XmlAttribute(name = "maximumRetries")
    protected Integer maximumRetries;
    @XmlAttribute(name = "retryDelay")
    protected Long retryDelay;
    @XmlAttribute(name = "maximumRetryDelay")
    protected Long maximumRetryDelay;
    @XmlAttribute(name = "exponentialBackOff")
    protected Boolean exponentialBackOff;
    @XmlAttribute(name = "randomBackOff")
    protected Boolean randomBackOff;

    /**
     * Gets the value of the maximumRetries property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMaximumRetries() {
        return maximumRetries;
    }

    /**
     * Sets the value of the maximumRetries property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaximumRetries(Integer value) {
        this.maximumRetries = value;
    }

    /**
     * Gets the value of the retryDelay property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getRetryDelay() {
        return retryDelay;
    }

    /**
     * Sets the value of the retryDelay property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setRetryDelay(Long value) {
        this.retryDelay = value;
    }

    /**
     * Gets the value of the maximumRetryDelay property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getMaximumRetryDelay() {
        return maximumRetryDelay;
    }

    /**
     * Sets the value of the maximumRetryDelay property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setMaximumRetryDelay(Long value) {
        this.maximumRetryDelay = value;
    }

    /**
     * Gets the value of the exponentialBackOff property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isExponentialBackOff() {
        return exponentialBackOff;
    }

    /**
     * Sets the value of the exponentialBackOff property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setExponentialBackOff(Boolean value) {
        this.exponentialBackOff = value;
    }

    /**
     * Gets the value of the randomBackOff property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRandomBackOff() {
        return randomBackOff;
    }

    /**
     * Sets the value of the randomBackOff property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRandomBackOff(Boolean value) {
        this.randomBackOff = value;
    }

}
