//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.13 at 12:09:41 PM EST 
//


package org.jboss.mapper.camel.blueprint;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for rollbackDefinition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="rollbackDefinition">
 *   &lt;complexContent>
 *     &lt;extension base="{http://camel.apache.org/schema/blueprint}noOutputDefinition">
 *       &lt;sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="markRollbackOnly" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="markRollbackOnlyLast" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="message" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;anyAttribute processContents='skip' namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "rollbackDefinition")
public class RollbackDefinition
    extends NoOutputDefinition
{

    @XmlAttribute(name = "markRollbackOnly")
    protected Boolean markRollbackOnly;
    @XmlAttribute(name = "markRollbackOnlyLast")
    protected Boolean markRollbackOnlyLast;
    @XmlAttribute(name = "message")
    protected String message;

    /**
     * Gets the value of the markRollbackOnly property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isMarkRollbackOnly() {
        return markRollbackOnly;
    }

    /**
     * Sets the value of the markRollbackOnly property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMarkRollbackOnly(Boolean value) {
        this.markRollbackOnly = value;
    }

    /**
     * Gets the value of the markRollbackOnlyLast property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isMarkRollbackOnlyLast() {
        return markRollbackOnlyLast;
    }

    /**
     * Sets the value of the markRollbackOnlyLast property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMarkRollbackOnlyLast(Boolean value) {
        this.markRollbackOnlyLast = value;
    }

    /**
     * Gets the value of the message property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessage() {
        return message;
    }

    /**
     * Sets the value of the message property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessage(String value) {
        this.message = value;
    }

}
