//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.13 at 12:09:41 PM EST 
//


package org.jboss.mapper.camel.blueprint;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for sslContextParametersFactoryBean complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sslContextParametersFactoryBean">
 *   &lt;complexContent>
 *     &lt;extension base="{http://camel.apache.org/schema/blueprint}abstractJsseUtilFactoryBean">
 *       &lt;all>
 *         &lt;element name="cipherSuites" type="{http://camel.apache.org/schema/blueprint}cipherSuitesParameters" minOccurs="0"/>
 *         &lt;element name="cipherSuitesFilter" type="{http://camel.apache.org/schema/blueprint}filterParameters" minOccurs="0"/>
 *         &lt;element name="secureSocketProtocols" type="{http://camel.apache.org/schema/blueprint}secureSocketProtocolsParameters" minOccurs="0"/>
 *         &lt;element name="secureSocketProtocolsFilter" type="{http://camel.apache.org/schema/blueprint}filterParameters" minOccurs="0"/>
 *         &lt;element name="keyManagers" type="{http://camel.apache.org/schema/blueprint}keyManagersParametersFactoryBean" minOccurs="0"/>
 *         &lt;element name="trustManagers" type="{http://camel.apache.org/schema/blueprint}trustManagersParametersFactoryBean" minOccurs="0"/>
 *         &lt;element name="secureRandom" type="{http://camel.apache.org/schema/blueprint}secureRandomParametersFactoryBean" minOccurs="0"/>
 *         &lt;element name="clientParameters" type="{http://camel.apache.org/schema/blueprint}sslContextClientParametersFactoryBean" minOccurs="0"/>
 *         &lt;element name="serverParameters" type="{http://camel.apache.org/schema/blueprint}sslContextServerParametersFactoryBean" minOccurs="0"/>
 *       &lt;/all>
 *       &lt;attribute name="sessionTimeout" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="provider" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="secureSocketProtocol" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="certAlias" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sslContextParametersFactoryBean", propOrder = {
    "cipherSuites",
    "cipherSuitesFilter",
    "secureSocketProtocols",
    "secureSocketProtocolsFilter",
    "keyManagers",
    "trustManagers",
    "secureRandom",
    "clientParameters",
    "serverParameters"
})
public class SslContextParametersFactoryBean
    extends AbstractJsseUtilFactoryBean
{

    protected CipherSuitesParameters cipherSuites;
    protected FilterParameters cipherSuitesFilter;
    protected SecureSocketProtocolsParameters secureSocketProtocols;
    protected FilterParameters secureSocketProtocolsFilter;
    protected KeyManagersParametersFactoryBean keyManagers;
    protected TrustManagersParametersFactoryBean trustManagers;
    protected SecureRandomParametersFactoryBean secureRandom;
    protected SslContextClientParametersFactoryBean clientParameters;
    protected SslContextServerParametersFactoryBean serverParameters;
    @XmlAttribute(name = "sessionTimeout")
    protected String sessionTimeout;
    @XmlAttribute(name = "provider")
    protected String provider;
    @XmlAttribute(name = "secureSocketProtocol")
    protected String secureSocketProtocol;
    @XmlAttribute(name = "certAlias")
    protected String certAlias;

    /**
     * Gets the value of the cipherSuites property.
     * 
     * @return
     *     possible object is
     *     {@link CipherSuitesParameters }
     *     
     */
    public CipherSuitesParameters getCipherSuites() {
        return cipherSuites;
    }

    /**
     * Sets the value of the cipherSuites property.
     * 
     * @param value
     *     allowed object is
     *     {@link CipherSuitesParameters }
     *     
     */
    public void setCipherSuites(CipherSuitesParameters value) {
        this.cipherSuites = value;
    }

    /**
     * Gets the value of the cipherSuitesFilter property.
     * 
     * @return
     *     possible object is
     *     {@link FilterParameters }
     *     
     */
    public FilterParameters getCipherSuitesFilter() {
        return cipherSuitesFilter;
    }

    /**
     * Sets the value of the cipherSuitesFilter property.
     * 
     * @param value
     *     allowed object is
     *     {@link FilterParameters }
     *     
     */
    public void setCipherSuitesFilter(FilterParameters value) {
        this.cipherSuitesFilter = value;
    }

    /**
     * Gets the value of the secureSocketProtocols property.
     * 
     * @return
     *     possible object is
     *     {@link SecureSocketProtocolsParameters }
     *     
     */
    public SecureSocketProtocolsParameters getSecureSocketProtocols() {
        return secureSocketProtocols;
    }

    /**
     * Sets the value of the secureSocketProtocols property.
     * 
     * @param value
     *     allowed object is
     *     {@link SecureSocketProtocolsParameters }
     *     
     */
    public void setSecureSocketProtocols(SecureSocketProtocolsParameters value) {
        this.secureSocketProtocols = value;
    }

    /**
     * Gets the value of the secureSocketProtocolsFilter property.
     * 
     * @return
     *     possible object is
     *     {@link FilterParameters }
     *     
     */
    public FilterParameters getSecureSocketProtocolsFilter() {
        return secureSocketProtocolsFilter;
    }

    /**
     * Sets the value of the secureSocketProtocolsFilter property.
     * 
     * @param value
     *     allowed object is
     *     {@link FilterParameters }
     *     
     */
    public void setSecureSocketProtocolsFilter(FilterParameters value) {
        this.secureSocketProtocolsFilter = value;
    }

    /**
     * Gets the value of the keyManagers property.
     * 
     * @return
     *     possible object is
     *     {@link KeyManagersParametersFactoryBean }
     *     
     */
    public KeyManagersParametersFactoryBean getKeyManagers() {
        return keyManagers;
    }

    /**
     * Sets the value of the keyManagers property.
     * 
     * @param value
     *     allowed object is
     *     {@link KeyManagersParametersFactoryBean }
     *     
     */
    public void setKeyManagers(KeyManagersParametersFactoryBean value) {
        this.keyManagers = value;
    }

    /**
     * Gets the value of the trustManagers property.
     * 
     * @return
     *     possible object is
     *     {@link TrustManagersParametersFactoryBean }
     *     
     */
    public TrustManagersParametersFactoryBean getTrustManagers() {
        return trustManagers;
    }

    /**
     * Sets the value of the trustManagers property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrustManagersParametersFactoryBean }
     *     
     */
    public void setTrustManagers(TrustManagersParametersFactoryBean value) {
        this.trustManagers = value;
    }

    /**
     * Gets the value of the secureRandom property.
     * 
     * @return
     *     possible object is
     *     {@link SecureRandomParametersFactoryBean }
     *     
     */
    public SecureRandomParametersFactoryBean getSecureRandom() {
        return secureRandom;
    }

    /**
     * Sets the value of the secureRandom property.
     * 
     * @param value
     *     allowed object is
     *     {@link SecureRandomParametersFactoryBean }
     *     
     */
    public void setSecureRandom(SecureRandomParametersFactoryBean value) {
        this.secureRandom = value;
    }

    /**
     * Gets the value of the clientParameters property.
     * 
     * @return
     *     possible object is
     *     {@link SslContextClientParametersFactoryBean }
     *     
     */
    public SslContextClientParametersFactoryBean getClientParameters() {
        return clientParameters;
    }

    /**
     * Sets the value of the clientParameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link SslContextClientParametersFactoryBean }
     *     
     */
    public void setClientParameters(SslContextClientParametersFactoryBean value) {
        this.clientParameters = value;
    }

    /**
     * Gets the value of the serverParameters property.
     * 
     * @return
     *     possible object is
     *     {@link SslContextServerParametersFactoryBean }
     *     
     */
    public SslContextServerParametersFactoryBean getServerParameters() {
        return serverParameters;
    }

    /**
     * Sets the value of the serverParameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link SslContextServerParametersFactoryBean }
     *     
     */
    public void setServerParameters(SslContextServerParametersFactoryBean value) {
        this.serverParameters = value;
    }

    /**
     * Gets the value of the sessionTimeout property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSessionTimeout() {
        return sessionTimeout;
    }

    /**
     * Sets the value of the sessionTimeout property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSessionTimeout(String value) {
        this.sessionTimeout = value;
    }

    /**
     * Gets the value of the provider property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProvider() {
        return provider;
    }

    /**
     * Sets the value of the provider property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProvider(String value) {
        this.provider = value;
    }

    /**
     * Gets the value of the secureSocketProtocol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecureSocketProtocol() {
        return secureSocketProtocol;
    }

    /**
     * Sets the value of the secureSocketProtocol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecureSocketProtocol(String value) {
        this.secureSocketProtocol = value;
    }

    /**
     * Gets the value of the certAlias property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCertAlias() {
        return certAlias;
    }

    /**
     * Sets the value of the certAlias property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCertAlias(String value) {
        this.certAlias = value;
    }

}
