//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.26 at 02:37:57 PM EST 
//


package org.jboss.mapper.camel.spring;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for aopDefinition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="aopDefinition">
 *   &lt;complexContent>
 *     &lt;extension base="{http://camel.apache.org/schema/spring}output">
 *       &lt;sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="beforeUri" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="afterUri" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="afterFinallyUri" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;anyAttribute processContents='skip' namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "aopDefinition")
public class AopDefinition
    extends Output
{

    @XmlAttribute(name = "beforeUri")
    protected String beforeUri;
    @XmlAttribute(name = "afterUri")
    protected String afterUri;
    @XmlAttribute(name = "afterFinallyUri")
    protected String afterFinallyUri;

    /**
     * Gets the value of the beforeUri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBeforeUri() {
        return beforeUri;
    }

    /**
     * Sets the value of the beforeUri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBeforeUri(String value) {
        this.beforeUri = value;
    }

    /**
     * Gets the value of the afterUri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAfterUri() {
        return afterUri;
    }

    /**
     * Sets the value of the afterUri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAfterUri(String value) {
        this.afterUri = value;
    }

    /**
     * Gets the value of the afterFinallyUri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAfterFinallyUri() {
        return afterFinallyUri;
    }

    /**
     * Sets the value of the afterFinallyUri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAfterFinallyUri(String value) {
        this.afterFinallyUri = value;
    }

}
