//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.26 at 02:37:57 PM EST 
//


package org.jboss.mapper.camel.spring;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for dataFormat complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="dataFormat">
 *   &lt;complexContent>
 *     &lt;extension base="{http://camel.apache.org/schema/spring}identifiedType">
 *       &lt;sequence>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "dataFormat")
@XmlSeeAlso({
    CryptoDataFormat.class,
    BeanioDataFormat.class,
    SoapJaxbDataFormat.class,
    AvroDataFormat.class,
    XmlSecurityDataFormat.class,
    JibxDataFormat.class,
    PgpDataFormat.class,
    SerializationDataFormat.class,
    BindyDataFormat.class,
    CsvDataFormat.class,
    CustomDataFormat.class,
    XmlBeansDataFormat.class,
    XStreamDataFormat.class,
    SyslogDataFormat.class,
    XmlJsonDataFormat.class,
    StringDataFormat.class,
    CastorDataFormat.class,
    RssDataFormat.class,
    GzipDataFormat.class,
    BarcodeDataFormat.class,
    ProtobufDataFormat.class,
    Hl7DataFormat.class,
    JaxbDataFormat.class,
    JsonDataFormat.class,
    ZipDataFormat.class,
    TidyMarkupDataFormat.class,
    FlatpackDataFormat.class,
    XmlRpcDataFormat.class,
    Base64DataFormat.class,
    ZipFileDataFormat.class
})
public class DataFormat
    extends IdentifiedType
{


}
