//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.26 at 02:37:57 PM EST 
//


package org.jboss.mapper.camel.spring;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for idempotentConsumerDefinition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="idempotentConsumerDefinition">
 *   &lt;complexContent>
 *     &lt;extension base="{http://camel.apache.org/schema/spring}expressionNode">
 *       &lt;sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="messageIdRepositoryRef" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="eager" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="skipDuplicate" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="removeOnFailure" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;anyAttribute processContents='skip' namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "idempotentConsumerDefinition")
public class IdempotentConsumerDefinition
    extends ExpressionNode
{

    @XmlAttribute(name = "messageIdRepositoryRef")
    protected String messageIdRepositoryRef;
    @XmlAttribute(name = "eager")
    protected Boolean eager;
    @XmlAttribute(name = "skipDuplicate")
    protected Boolean skipDuplicate;
    @XmlAttribute(name = "removeOnFailure")
    protected Boolean removeOnFailure;

    /**
     * Gets the value of the messageIdRepositoryRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageIdRepositoryRef() {
        return messageIdRepositoryRef;
    }

    /**
     * Sets the value of the messageIdRepositoryRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageIdRepositoryRef(String value) {
        this.messageIdRepositoryRef = value;
    }

    /**
     * Gets the value of the eager property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isEager() {
        return eager;
    }

    /**
     * Sets the value of the eager property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEager(Boolean value) {
        this.eager = value;
    }

    /**
     * Gets the value of the skipDuplicate property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSkipDuplicate() {
        return skipDuplicate;
    }

    /**
     * Sets the value of the skipDuplicate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSkipDuplicate(Boolean value) {
        this.skipDuplicate = value;
    }

    /**
     * Gets the value of the removeOnFailure property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRemoveOnFailure() {
        return removeOnFailure;
    }

    /**
     * Sets the value of the removeOnFailure property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRemoveOnFailure(Boolean value) {
        this.removeOnFailure = value;
    }

}
