//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.26 at 02:37:57 PM EST 
//


package org.jboss.mapper.camel.spring;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for jsonLibrary.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="jsonLibrary">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Jackson"/>
 *     &lt;enumeration value="XStream"/>
 *     &lt;enumeration value="Gson"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "jsonLibrary")
@XmlEnum
public enum JsonLibrary {

    @XmlEnumValue("Jackson")
    JACKSON("Jackson"),
    @XmlEnumValue("XStream")
    X_STREAM("XStream"),
    @XmlEnumValue("Gson")
    GSON("Gson");
    private final String value;

    JsonLibrary(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static JsonLibrary fromValue(String v) {
        for (JsonLibrary c: JsonLibrary.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
