//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.26 at 02:37:57 PM EST 
//


package org.jboss.mapper.camel.spring;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for redeliveryPolicyDefinition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="redeliveryPolicyDefinition">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="maximumRedeliveries" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="redeliveryDelay" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="asyncDelayedRedelivery" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="backOffMultiplier" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="useExponentialBackOff" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="collisionAvoidanceFactor" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="useCollisionAvoidance" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="maximumRedeliveryDelay" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="retriesExhaustedLogLevel" type="{http://camel.apache.org/schema/spring}loggingLevel" />
 *       &lt;attribute name="retryAttemptedLogLevel" type="{http://camel.apache.org/schema/spring}loggingLevel" />
 *       &lt;attribute name="logRetryAttempted" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="logStackTrace" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="logRetryStackTrace" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="logHandled" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="logContinued" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="logExhausted" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="logExhaustedMessageHistory" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="disableRedelivery" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="delayPattern" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="allowRedeliveryWhileStopping" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "redeliveryPolicyDefinition")
public class RedeliveryPolicyDefinition {

    @XmlAttribute(name = "maximumRedeliveries")
    protected String maximumRedeliveries;
    @XmlAttribute(name = "redeliveryDelay")
    protected String redeliveryDelay;
    @XmlAttribute(name = "asyncDelayedRedelivery")
    protected String asyncDelayedRedelivery;
    @XmlAttribute(name = "backOffMultiplier")
    protected String backOffMultiplier;
    @XmlAttribute(name = "useExponentialBackOff")
    protected String useExponentialBackOff;
    @XmlAttribute(name = "collisionAvoidanceFactor")
    protected String collisionAvoidanceFactor;
    @XmlAttribute(name = "useCollisionAvoidance")
    protected String useCollisionAvoidance;
    @XmlAttribute(name = "maximumRedeliveryDelay")
    protected String maximumRedeliveryDelay;
    @XmlAttribute(name = "retriesExhaustedLogLevel")
    protected LoggingLevel retriesExhaustedLogLevel;
    @XmlAttribute(name = "retryAttemptedLogLevel")
    protected LoggingLevel retryAttemptedLogLevel;
    @XmlAttribute(name = "logRetryAttempted")
    protected String logRetryAttempted;
    @XmlAttribute(name = "logStackTrace")
    protected String logStackTrace;
    @XmlAttribute(name = "logRetryStackTrace")
    protected String logRetryStackTrace;
    @XmlAttribute(name = "logHandled")
    protected String logHandled;
    @XmlAttribute(name = "logContinued")
    protected String logContinued;
    @XmlAttribute(name = "logExhausted")
    protected String logExhausted;
    @XmlAttribute(name = "logExhaustedMessageHistory")
    protected String logExhaustedMessageHistory;
    @XmlAttribute(name = "disableRedelivery")
    protected String disableRedelivery;
    @XmlAttribute(name = "delayPattern")
    protected String delayPattern;
    @XmlAttribute(name = "allowRedeliveryWhileStopping")
    protected String allowRedeliveryWhileStopping;

    /**
     * Gets the value of the maximumRedeliveries property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaximumRedeliveries() {
        return maximumRedeliveries;
    }

    /**
     * Sets the value of the maximumRedeliveries property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaximumRedeliveries(String value) {
        this.maximumRedeliveries = value;
    }

    /**
     * Gets the value of the redeliveryDelay property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRedeliveryDelay() {
        return redeliveryDelay;
    }

    /**
     * Sets the value of the redeliveryDelay property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRedeliveryDelay(String value) {
        this.redeliveryDelay = value;
    }

    /**
     * Gets the value of the asyncDelayedRedelivery property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAsyncDelayedRedelivery() {
        return asyncDelayedRedelivery;
    }

    /**
     * Sets the value of the asyncDelayedRedelivery property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAsyncDelayedRedelivery(String value) {
        this.asyncDelayedRedelivery = value;
    }

    /**
     * Gets the value of the backOffMultiplier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBackOffMultiplier() {
        return backOffMultiplier;
    }

    /**
     * Sets the value of the backOffMultiplier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBackOffMultiplier(String value) {
        this.backOffMultiplier = value;
    }

    /**
     * Gets the value of the useExponentialBackOff property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUseExponentialBackOff() {
        return useExponentialBackOff;
    }

    /**
     * Sets the value of the useExponentialBackOff property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUseExponentialBackOff(String value) {
        this.useExponentialBackOff = value;
    }

    /**
     * Gets the value of the collisionAvoidanceFactor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCollisionAvoidanceFactor() {
        return collisionAvoidanceFactor;
    }

    /**
     * Sets the value of the collisionAvoidanceFactor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCollisionAvoidanceFactor(String value) {
        this.collisionAvoidanceFactor = value;
    }

    /**
     * Gets the value of the useCollisionAvoidance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUseCollisionAvoidance() {
        return useCollisionAvoidance;
    }

    /**
     * Sets the value of the useCollisionAvoidance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUseCollisionAvoidance(String value) {
        this.useCollisionAvoidance = value;
    }

    /**
     * Gets the value of the maximumRedeliveryDelay property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaximumRedeliveryDelay() {
        return maximumRedeliveryDelay;
    }

    /**
     * Sets the value of the maximumRedeliveryDelay property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaximumRedeliveryDelay(String value) {
        this.maximumRedeliveryDelay = value;
    }

    /**
     * Gets the value of the retriesExhaustedLogLevel property.
     * 
     * @return
     *     possible object is
     *     {@link LoggingLevel }
     *     
     */
    public LoggingLevel getRetriesExhaustedLogLevel() {
        return retriesExhaustedLogLevel;
    }

    /**
     * Sets the value of the retriesExhaustedLogLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link LoggingLevel }
     *     
     */
    public void setRetriesExhaustedLogLevel(LoggingLevel value) {
        this.retriesExhaustedLogLevel = value;
    }

    /**
     * Gets the value of the retryAttemptedLogLevel property.
     * 
     * @return
     *     possible object is
     *     {@link LoggingLevel }
     *     
     */
    public LoggingLevel getRetryAttemptedLogLevel() {
        return retryAttemptedLogLevel;
    }

    /**
     * Sets the value of the retryAttemptedLogLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link LoggingLevel }
     *     
     */
    public void setRetryAttemptedLogLevel(LoggingLevel value) {
        this.retryAttemptedLogLevel = value;
    }

    /**
     * Gets the value of the logRetryAttempted property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogRetryAttempted() {
        return logRetryAttempted;
    }

    /**
     * Sets the value of the logRetryAttempted property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogRetryAttempted(String value) {
        this.logRetryAttempted = value;
    }

    /**
     * Gets the value of the logStackTrace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogStackTrace() {
        return logStackTrace;
    }

    /**
     * Sets the value of the logStackTrace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogStackTrace(String value) {
        this.logStackTrace = value;
    }

    /**
     * Gets the value of the logRetryStackTrace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogRetryStackTrace() {
        return logRetryStackTrace;
    }

    /**
     * Sets the value of the logRetryStackTrace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogRetryStackTrace(String value) {
        this.logRetryStackTrace = value;
    }

    /**
     * Gets the value of the logHandled property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogHandled() {
        return logHandled;
    }

    /**
     * Sets the value of the logHandled property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogHandled(String value) {
        this.logHandled = value;
    }

    /**
     * Gets the value of the logContinued property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogContinued() {
        return logContinued;
    }

    /**
     * Sets the value of the logContinued property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogContinued(String value) {
        this.logContinued = value;
    }

    /**
     * Gets the value of the logExhausted property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogExhausted() {
        return logExhausted;
    }

    /**
     * Sets the value of the logExhausted property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogExhausted(String value) {
        this.logExhausted = value;
    }

    /**
     * Gets the value of the logExhaustedMessageHistory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogExhaustedMessageHistory() {
        return logExhaustedMessageHistory;
    }

    /**
     * Sets the value of the logExhaustedMessageHistory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogExhaustedMessageHistory(String value) {
        this.logExhaustedMessageHistory = value;
    }

    /**
     * Gets the value of the disableRedelivery property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisableRedelivery() {
        return disableRedelivery;
    }

    /**
     * Sets the value of the disableRedelivery property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisableRedelivery(String value) {
        this.disableRedelivery = value;
    }

    /**
     * Gets the value of the delayPattern property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDelayPattern() {
        return delayPattern;
    }

    /**
     * Sets the value of the delayPattern property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDelayPattern(String value) {
        this.delayPattern = value;
    }

    /**
     * Gets the value of the allowRedeliveryWhileStopping property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAllowRedeliveryWhileStopping() {
        return allowRedeliveryWhileStopping;
    }

    /**
     * Sets the value of the allowRedeliveryWhileStopping property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAllowRedeliveryWhileStopping(String value) {
        this.allowRedeliveryWhileStopping = value;
    }

}
