//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.26 at 02:37:57 PM EST 
//


package org.jboss.mapper.camel.spring;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for throttleDefinition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="throttleDefinition">
 *   &lt;complexContent>
 *     &lt;extension base="{http://camel.apache.org/schema/spring}expressionNode">
 *       &lt;sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="executorServiceRef" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="timePeriodMillis" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="asyncDelayed" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="callerRunsWhenRejected" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="rejectExecution" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;anyAttribute processContents='skip' namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "throttleDefinition")
public class ThrottleDefinition
    extends ExpressionNode
{

    @XmlAttribute(name = "executorServiceRef")
    protected String executorServiceRef;
    @XmlAttribute(name = "timePeriodMillis")
    protected Long timePeriodMillis;
    @XmlAttribute(name = "asyncDelayed")
    protected Boolean asyncDelayed;
    @XmlAttribute(name = "callerRunsWhenRejected")
    protected Boolean callerRunsWhenRejected;
    @XmlAttribute(name = "rejectExecution")
    protected Boolean rejectExecution;

    /**
     * Gets the value of the executorServiceRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExecutorServiceRef() {
        return executorServiceRef;
    }

    /**
     * Sets the value of the executorServiceRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExecutorServiceRef(String value) {
        this.executorServiceRef = value;
    }

    /**
     * Gets the value of the timePeriodMillis property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getTimePeriodMillis() {
        return timePeriodMillis;
    }

    /**
     * Sets the value of the timePeriodMillis property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setTimePeriodMillis(Long value) {
        this.timePeriodMillis = value;
    }

    /**
     * Gets the value of the asyncDelayed property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAsyncDelayed() {
        return asyncDelayed;
    }

    /**
     * Sets the value of the asyncDelayed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAsyncDelayed(Boolean value) {
        this.asyncDelayed = value;
    }

    /**
     * Gets the value of the callerRunsWhenRejected property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCallerRunsWhenRejected() {
        return callerRunsWhenRejected;
    }

    /**
     * Sets the value of the callerRunsWhenRejected property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCallerRunsWhenRejected(Boolean value) {
        this.callerRunsWhenRejected = value;
    }

    /**
     * Gets the value of the rejectExecution property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRejectExecution() {
        return rejectExecution;
    }

    /**
     * Sets the value of the rejectExecution property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRejectExecution(Boolean value) {
        this.rejectExecution = value;
    }

}
