//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.26 at 02:37:57 PM EST 
//


package org.jboss.mapper.camel.spring;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tokenizerExpression complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tokenizerExpression">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://camel.apache.org/schema/spring>expression">
 *       &lt;attribute name="token" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="endToken" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="inheritNamespaceTagName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="headerName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="regex" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="xml" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="includeTokens" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="group" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tokenizerExpression")
public class TokenizerExpression
    extends Expression
{

    @XmlAttribute(name = "token", required = true)
    protected String token;
    @XmlAttribute(name = "endToken")
    protected String endToken;
    @XmlAttribute(name = "inheritNamespaceTagName")
    protected String inheritNamespaceTagName;
    @XmlAttribute(name = "headerName")
    protected String headerName;
    @XmlAttribute(name = "regex")
    protected Boolean regex;
    @XmlAttribute(name = "xml")
    protected Boolean xml;
    @XmlAttribute(name = "includeTokens")
    protected Boolean includeTokens;
    @XmlAttribute(name = "group")
    protected Integer group;

    /**
     * Gets the value of the token property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToken() {
        return token;
    }

    /**
     * Sets the value of the token property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToken(String value) {
        this.token = value;
    }

    /**
     * Gets the value of the endToken property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndToken() {
        return endToken;
    }

    /**
     * Sets the value of the endToken property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndToken(String value) {
        this.endToken = value;
    }

    /**
     * Gets the value of the inheritNamespaceTagName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInheritNamespaceTagName() {
        return inheritNamespaceTagName;
    }

    /**
     * Sets the value of the inheritNamespaceTagName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInheritNamespaceTagName(String value) {
        this.inheritNamespaceTagName = value;
    }

    /**
     * Gets the value of the headerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHeaderName() {
        return headerName;
    }

    /**
     * Sets the value of the headerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHeaderName(String value) {
        this.headerName = value;
    }

    /**
     * Gets the value of the regex property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRegex() {
        return regex;
    }

    /**
     * Sets the value of the regex property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRegex(Boolean value) {
        this.regex = value;
    }

    /**
     * Gets the value of the xml property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isXml() {
        return xml;
    }

    /**
     * Sets the value of the xml property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setXml(Boolean value) {
        this.xml = value;
    }

    /**
     * Gets the value of the includeTokens property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIncludeTokens() {
        return includeTokens;
    }

    /**
     * Sets the value of the includeTokens property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIncludeTokens(Boolean value) {
        this.includeTokens = value;
    }

    /**
     * Gets the value of the group property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getGroup() {
        return group;
    }

    /**
     * Sets the value of the group property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setGroup(Integer value) {
        this.group = value;
    }

}
