//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.26 at 02:37:57 PM EST 
//


package org.jboss.mapper.camel.spring;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for weightedLoadBalancerDefinition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="weightedLoadBalancerDefinition">
 *   &lt;complexContent>
 *     &lt;extension base="{http://camel.apache.org/schema/spring}loadBalancer">
 *       &lt;sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="roundRobin" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="distributionRatio" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="distributionRatioDelimiter" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "weightedLoadBalancerDefinition")
public class WeightedLoadBalancerDefinition
    extends LoadBalancer
{

    @XmlAttribute(name = "roundRobin")
    protected Boolean roundRobin;
    @XmlAttribute(name = "distributionRatio", required = true)
    protected String distributionRatio;
    @XmlAttribute(name = "distributionRatioDelimiter")
    protected String distributionRatioDelimiter;

    /**
     * Gets the value of the roundRobin property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRoundRobin() {
        return roundRobin;
    }

    /**
     * Sets the value of the roundRobin property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRoundRobin(Boolean value) {
        this.roundRobin = value;
    }

    /**
     * Gets the value of the distributionRatio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDistributionRatio() {
        return distributionRatio;
    }

    /**
     * Sets the value of the distributionRatio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDistributionRatio(String value) {
        this.distributionRatio = value;
    }

    /**
     * Gets the value of the distributionRatioDelimiter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDistributionRatioDelimiter() {
        return distributionRatioDelimiter;
    }

    /**
     * Sets the value of the distributionRatioDelimiter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDistributionRatioDelimiter(String value) {
        this.distributionRatioDelimiter = value;
    }

}
